Repository IDI-Systems/acre2, pull requests merged in 2018-06, with the labels that each got.

#539 Fix German Translation
  addons/sys_intercom/stringtable.xml
Labels: translation

#542 Intercoms - Don't run configIntercom if no intercoms exist
  addons/sys_intercom/fnc_configIntercom.sqf
  addons/sys_intercom/fnc_initVehicleIntercom.sqf
Labels: bug fix, enhancement

#540 Document new API functions for Racks
  docs/wiki/frameworks/vehicle-racks.md
Labels: documentation

#548 Increase required Arma 3 to 1.82 and CBA to 3.7.1
  addons/main/script_mod.hpp
Labels: task

#527 Cleanup documentation for 2.6.0
  docs/wiki/frameworks/vehicle-intercom.md
  docs/wiki/frameworks/vehicle-racks.md
  docs/wiki/user/external-radios.md
  docs/wiki/user/vehicle-intercom.md
  docs/wiki/user/vehicle-racks.md
Labels: cleanup, documentation

#550 Fix not being able to unmount radio
  addons/sys_rack/fnc_rackChildrenActions.sqf
Labels: bug fix

#551 Fix addRackToVehicle
  addons/api/fnc_addRackToVehicle.sqf
Labels: bug fix

#543 Enable channel fast switch for racked radios
  addons/sys_core/fnc_switchChannelFast.sqf
Labels: enhancement

#545 Added actions to use and stop using all racks
  addons/ace_interact/fnc_radioListChildrenActions.sqf
  addons/sys_rack/fnc_rackListChildrenActions.sqf
  addons/sys_rack/stringtable.xml
Labels: enhancement
