Repository IDI-Systems/acre2, pull requests merged in 2018-02, with the labels that each got.

#484 Improve Vehicle Info UI
  addons/ace_interact/fnc_radioChildrenActions.sqf
  addons/ace_interact/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gui/AcreVehInfoControls.hpp
  addons/sys_gui/CfgRscTitles.hpp
  addons/sys_gui/CfgUIGrids.hpp
  addons/sys_gui/CfgVolumeControl.hpp
  addons/sys_gui/XEH_missionDisplayLoad.sqf
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_gui/config.cpp
  addons/sys_gui/data/ui/IGUI_vehicleInfo_preview_ca.paa
  addons/sys_gui/fnc_onVolumeControlKeyPress.sqf
  addons/sys_gui/fnc_onVolumeControlKeyPressUp.sqf
  addons/sys_gui/fnc_openVolumeControl.sqf
  addons/sys_gui/fnc_updateVehicleInfo.sqf
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/XEH_PREP.hpp
  addons/sys_intercom/fnc_handleBroadcasting.sqf
  addons/sys_intercom/fnc_handlePttKeyPress.sqf
  addons/sys_intercom/fnc_handlePttKeyPressUp.sqf
  addons/sys_intercom/fnc_infantryPhoneChildrenActions.sqf
  addons/sys_intercom/fnc_intercomChildrenActions.sqf
  addons/sys_intercom/fnc_seatSwitched.sqf
  addons/sys_intercom/fnc_setRackRxTxCapabilities.sqf
  addons/sys_intercom/fnc_setStationConfiguration.sqf
  addons/sys_intercom/fnc_updateVehicleInfoText.sqf
  addons/sys_intercom/script_component.hpp
  addons/sys_intercom/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/CfgVehicles.hpp
  addons/sys_rack/fnc_enterVehicle.sqf
  addons/sys_rack/fnc_generateMountableRadioActions.sqf
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/fnc_startUsingMountedRadio.sqf
  addons/sys_rack/fnc_stopUsingMountedRadio.sqf
  addons/sys_rack/stringtable.xml
Labels: enhancement

#487 Submenu for Rx and Tx functionality
  addons/ace_interact/XEH_PREP.hpp
  addons/ace_interact/fnc_generateRxTxChildrenActions.sqf
  addons/ace_interact/fnc_generateSpatialChildrenActions.sqf
  addons/ace_interact/fnc_radioChildrenActions.sqf
  addons/ace_interact/fnc_radioListChildrenActions.sqf
  addons/ace_interact/fnc_radioPTTChildrenActions.sqf
  addons/sys_external/fnc_childrenActions.sqf
  addons/sys_intercom/XEH_PREP.hpp
  addons/sys_intercom/fnc_infantryPhoneChildrenActions.sqf
  addons/sys_intercom/fnc_intercomChildrenActions.sqf
  addons/sys_intercom/fnc_intercomListChildrenActions.sqf
  addons/sys_intercom/fnc_intercomListRxTxActions.sqf
  addons/sys_rack/fnc_rackChildrenActions.sqf
Labels: enhancement, ignore changelog

#360 Proper initialisation of racks & new api functions
  addons/api/CfgFunctions.hpp
  addons/api/fnc_addRackToVehicle.sqf
  addons/api/fnc_areVehicleRacksInitialized.sqf
  addons/api/fnc_initVehicleRacks.sqf
  addons/api/fnc_isRackRadioRemovable.sqf
  addons/api/fnc_mountRackRadio.sqf
  addons/api/fnc_removeRackFromVehicle.sqf
  addons/api/fnc_unmountRackRadio.sqf
  addons/sys_intercom/fnc_configRackRxTxCapabilities.sqf
  addons/sys_rack/XEH_postInit.sqf
  addons/sys_rack/fnc_addRack.sqf
  addons/sys_rack/fnc_getWiredIntercoms.sqf
  addons/sys_rack/fnc_initActionVehicle.sqf
  addons/sys_rack/fnc_onReturnRackId.sqf
  addons/sys_rack/fnc_onReturnRadioId.sqf
Labels: bug fix, enhancement

#488 Preset PRC-77
  addons/sys_prc77/functions/fnc_preset_information.sqf
Labels: bug fix, trivial

#482 Don't recompile XEH Display EH's before every call
  addons/sys_core/CfgEventHandlers.hpp
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_spectatorEGDisplayLoad.sqf
  addons/sys_core/XEH_spectatorEGDisplayUnload.sqf
  addons/sys_core/fnc_spectatorEGDisplayLoad.sqf
  addons/sys_core/fnc_spectatorEGDisplayUnload.sqf
  addons/sys_gui/CfgEventHandlers.hpp
  addons/sys_gui/XEH_PREP.hpp
  addons/sys_gui/XEH_missionDisplayLoad.sqf
  addons/sys_gui/fnc_missionDisplayLoad.sqf
  addons/sys_intercom/fnc_intercomListRxTxActions.sqf
  addons/sys_io/CfgEventHandlers.hpp
  addons/sys_io/XEH_PREP.hpp
  addons/sys_io/XEH_missionDisplayLoad.sqf
  addons/sys_io/fnc_missionDisplayLoad.sqf
Labels: bug fix, optimization

#480 AN/VRC-64
  addons/sys_antenna/CfgAcreComponents.hpp
  addons/sys_antenna/binary/AS-1729_VRC_gain.aba
  addons/sys_prc77/radio/fnc_getCurrentChannelData.sqf
  addons/sys_prc77/radio/fnc_initializeRadio.sqf
  addons/sys_prc77/script_component.hpp
  addons/sys_rack/CfgAcreRacks.hpp
  addons/sys_rack/CfgVehicles.hpp
  addons/sys_rack/XEH_PREP.hpp
  addons/sys_rack/script_acre_rack_defines.hpp
  addons/sys_rack/vrc64/__PREP__.sqf
  addons/sys_rack/vrc64/fnc_vrc64MountRadio.sqf
  addons/sys_rack/vrc64/fnc_vrc64MountableRadio.sqf
  addons/sys_rack/vrc64/fnc_vrc64UnmountRadio.sqf
  addons/sys_rack/vrc64/script_component.hpp
  extras/antennas/AS-1729_VRC.inp
  extras/antennas/AS-1729_VRC.nec
Labels: enhancement

#490 Fix infantry phone warning
  addons/sys_intercom/fnc_configInfantryPhone.sqf
Labels: bug fix

#492 Remove component warning in racks
  addons/sys_rack/CfgAcreRacks.hpp
  addons/sys_rack/XEH_PREP.hpp
  addons/sys_rack/fnc_attachComponent.sqf
Labels: cleanup, ignore changelog

#491 Master station pass
  addons/sys_intercom/CfgVehicles.hpp
Labels: enhancement

#493 Cleanup of intercom stringtable + spanish translation
  addons/sys_intercom/stringtable.xml
Labels: cleanup, enhancement

#495 Fix infantry phone configuration and actions
  addons/sys_intercom/fnc_configInfantryPhone.sqf
  addons/sys_intercom/fnc_infantryPhoneChildrenActions.sqf
  addons/sys_intercom/fnc_isInfantryPhoneSpeakerAvailable.sqf
Labels: bug fix
