Repository IDI-Systems/acre2, pull requests merged in 2018-11, with the labels that each got.

#608 Fix function getGear
  addons/sys_core/fnc_getGear.sqf
Labels: bug fix

#607 Introduce factor for AI revealing
  addons/api/fnc_getRevealToAI.sqf
  addons/api/fnc_setRevealToAI.sqf
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/fnc_enableRevealAI.sqf
  addons/sys_core/initSettings.sqf
Labels: enhancement

#498 Antenna automatic elevation
  addons/ace_interact/fnc_radioListChildrenActions.sqf
  addons/ace_interact/stringtable.xml
  addons/sys_components/XEH_PREP.hpp
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_components/fnc_getAntennaUpVector.sqf
  addons/sys_components/fnc_handleComponentMessage.sqf
  addons/sys_components/fnc_toggleAntennaDir.sqf
  addons/sys_components/script_component.hpp
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/initSettings.sqf
  addons/sys_core/stringtable.xml
  addons/sys_gui/CfgRscTitles.hpp
  addons/sys_gui/CfgUIGrids.hpp
  addons/sys_gui/XEH_PREP.hpp
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_gui/XEH_preInit.sqf
  addons/sys_gui/data/ui/crouch_bend.paa
  addons/sys_gui/data/ui/crouch_straight.paa
  addons/sys_gui/data/ui/prone_bend.paa
  addons/sys_gui/data/ui/prone_straight.paa
  addons/sys_gui/data/ui/stand_bend.paa
  addons/sys_gui/data/ui/stand_straight.paa
  addons/sys_gui/fnc_antennaElevationDisplay.sqf
  docs/images/user/antenna_indicator.png
  docs/wiki/user/radio-signal-loss.md
  extras/logos/AntennaIndicator.psd
Labels: enhancement

#609 Fix UI Stuff
  addons/sys_gui/CfgUIGrids.hpp
  addons/sys_list/data/ui/IGUI_notification_preview_ca.paa
  addons/sys_list/data/ui/IGUI_notification_preview_ca.png
Labels: bug fix

#599 Cleanup 2.7.0 deprecated features/code 2
  addons/api/CfgFunctions.hpp
  addons/api/CfgModules.hpp
  addons/api/fnc_difficultySettings.sqf
  addons/api/fnc_ignoreAntennaDirection.sqf
  addons/api/fnc_isBroadcasting.sqf
  addons/api/fnc_setFullDuplex.sqf
  addons/api/fnc_setInterference.sqf
  addons/api/fnc_setLossModelScale.sqf
  addons/api/fnc_setRevealToAI.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/fnc_ignoreAntennaDirection.sqf
  addons/sys_core/fnc_setFullDuplex.sqf
  addons/sys_core/fnc_setInterference.sqf
  addons/sys_core/fnc_setLossModelScale.sqf
  addons/sys_core/fnc_setRevealToAI.sqf
  addons/sys_core/initSettings.sqf
  docs/wiki/user/basic-concepts.md
  docs/wiki/user/radio-signal-loss.md
Labels: cleanup, task

#610 Fix Antenna log typo
  addons/sys_antenna/XEH_postInit.sqf
Labels: bug fix
