Repository IDI-Systems/acre2, pull requests merged in 2018-08, with the labels that each got.

#560 Fix make.py for newer Mikero tools
  tools/make.py
Labels: tools

#571 Add Start/Stop Speaking CBA Events
  addons/sys_core/fnc_localStartSpeaking.sqf
  addons/sys_core/fnc_localStopSpeaking.sqf
  docs/_data/sidebar.yml
  docs/wiki/frameworks/events-list.md
Labels: feature request

#573 Cleanup 2.7.0 deprecated features/code
  addons/api/CfgFunctions.hpp
  addons/api/CfgModules.hpp
  addons/api/fnc_difficultySettings.sqf
  addons/api/fnc_ignoreAntennaDirection.sqf
  addons/api/fnc_isBroadcasting.sqf
  addons/api/fnc_setFullDuplex.sqf
  addons/api/fnc_setInterference.sqf
  addons/api/fnc_setLossModelScale.sqf
  addons/api/fnc_setRevealToAI.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/fnc_ignoreAntennaDirection.sqf
  addons/sys_core/fnc_setFullDuplex.sqf
  addons/sys_core/fnc_setInterference.sqf
  addons/sys_core/fnc_setLossModelScale.sqf
  addons/sys_core/fnc_setRevealToAI.sqf
  addons/sys_core/initSettings.sqf
  docs/wiki/user/basic-concepts.md
  docs/wiki/user/radio-signal-loss.md
Labels: cleanup

#569 Small optimisation and formatting in sys_core
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_addGear.sqf
  addons/sys_core/fnc_callExt.sqf
  addons/sys_core/fnc_canUnderstand.sqf
  addons/sys_core/fnc_coreInitPFH.sqf
  addons/sys_core/fnc_getAlive.sqf
  addons/sys_core/fnc_getCompartment.sqf
  addons/sys_core/fnc_getGear.sqf
  addons/sys_core/fnc_getSpeakingLanguageId.sqf
  addons/sys_core/fnc_handleGetHeadVector.sqf
  addons/sys_core/fnc_handleMultiPttKeyPress.sqf
  addons/sys_core/fnc_localStartSpeaking.sqf
  addons/sys_core/fnc_muting.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_processRadioSpeaker.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_core/fnc_remoteStopSpeaking.sqf
  addons/sys_core/fnc_replaceGear.sqf
  addons/sys_core/fnc_showBroadCastHint.sqf
  addons/sys_core/fnc_speaking.sqf
Labels: optimization
