Repository IDI-Systems/acre2, pull requests merged in 2018-10, with the labels that each got.

#586 Spanish translations
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation

#587 Cleanup sys_components
  addons/sys_components/fnc_attachComponentHandler.sqf
  addons/sys_components/fnc_attachSimpleComponent.sqf
  addons/sys_components/fnc_connectorConnected.sqf
  addons/sys_components/fnc_detachComponent.sqf
  addons/sys_components/fnc_detachComponentHandler.sqf
  addons/sys_components/fnc_findAntenna.sqf
  addons/sys_components/fnc_getAllAvailableConnectors.sqf
  addons/sys_components/fnc_getAllConnectedComponents.sqf
  addons/sys_components/fnc_getAllConnectors.sqf
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_components/fnc_getComponentTree.sqf
  addons/sys_components/fnc_getConnectorSpecification.sqf
  addons/sys_components/fnc_handleComponentMessage.sqf
  addons/sys_components/fnc_initializeComponent.sqf
Labels: cleanup

#589 Cleanup and document sys_radio component
  addons/sys_radio/XEH_PREP.hpp
  addons/sys_radio/fnc_canUnitReceive.sqf
  addons/sys_radio/fnc_canUnitTransmit.sqf
  addons/sys_radio/fnc_getRadioObject.sqf
  addons/sys_radio/fnc_getRadioPos.sqf
  addons/sys_radio/fnc_getRadioSpatial.sqf
  addons/sys_radio/fnc_getRadioSubObject.sqf
  addons/sys_radio/fnc_getRadioVolume.sqf
  addons/sys_radio/fnc_handleRadioSpatialKeyPressed.sqf
  addons/sys_radio/fnc_initDefaultRadio.sqf
  addons/sys_radio/fnc_monitorRadios.sqf
  addons/sys_radio/fnc_monitorRadiosPFH.sqf
  addons/sys_radio/fnc_nearRadios.sqf
  addons/sys_radio/fnc_onDialogClose.sqf
  addons/sys_radio/fnc_onPlayerKilled.sqf
  addons/sys_radio/fnc_onReturnRadioId.sqf
  addons/sys_radio/fnc_openRadio.sqf
  addons/sys_radio/fnc_playRadioSound.sqf
  addons/sys_radio/fnc_radioExists.sqf
  addons/sys_radio/fnc_setActiveRadio.sqf
  addons/sys_radio/fnc_setRadioSpatial.sqf
  addons/sys_radio/fnc_setRadioVolume.sqf
  addons/sys_radio/fnc_stopUsingRadio.sqf
Labels: cleanup, documentation

#593 sys_rack cleanup
  addons/sys_rack/XEH_postInit.sqf
  addons/sys_rack/fnc_generateMountableRadioActions.sqf
  addons/sys_rack/fnc_getMountableRadios.sqf
  addons/sys_rack/fnc_getState.sqf
  addons/sys_rack/fnc_rackPFH.sqf
  addons/sys_rack/fnc_setState.sqf
Labels: cleanup, needs testing

#596 Update French translation
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation

#591 Cleanup of sys_external
  addons/sys_external/fnc_checkListChildrenActions.sqf
  addons/sys_external/fnc_childrenActions.sqf
  addons/sys_external/fnc_externalRadioPFH.sqf
  addons/sys_external/fnc_getSharedExternalRadios.sqf
  addons/sys_external/fnc_isExternalActionAvailable.sqf
  addons/sys_external/fnc_startUsingExternalRadio.sqf
Labels: cleanup

#582 Hide Vehicle Info UI in Feature Cameras
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_rack/XEH_postInit.sqf
Labels: enhancement

#598 Revert "Cleanup 2.7.0 deprecated features/code (#573)" for 2.6.2
  addons/api/CfgFunctions.hpp
  addons/api/CfgModules.hpp
  addons/api/fnc_difficultySettings.sqf
  addons/api/fnc_ignoreAntennaDirection.sqf
  addons/api/fnc_isBroadcasting.sqf
  addons/api/fnc_setFullDuplex.sqf
  addons/api/fnc_setInterference.sqf
  addons/api/fnc_setLossModelScale.sqf
  addons/api/fnc_setRevealToAI.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/fnc_ignoreAntennaDirection.sqf
  addons/sys_core/fnc_setFullDuplex.sqf
  addons/sys_core/fnc_setInterference.sqf
  addons/sys_core/fnc_setLossModelScale.sqf
  addons/sys_core/fnc_setRevealToAI.sqf
  addons/sys_core/initSettings.sqf
  docs/wiki/user/basic-concepts.md
  docs/wiki/user/radio-signal-loss.md
Labels: task

#594 Cleanup of sys_server
  addons/sys_server/fnc_acknowledgeId.sqf
  addons/sys_server/fnc_clientIntentToGarbageCollect.sqf
  addons/sys_server/fnc_collect.sqf
  addons/sys_server/fnc_doAddComponentCargo.sqf
  addons/sys_server/fnc_getRadioId.sqf
  addons/sys_server/fnc_masterIdTracker.sqf
  addons/sys_server/fnc_onGetRadioId.sqf
Labels: cleanup

#601 Fix Notification Spam
  addons/sys_io/fnc_server.sqf
Labels: enhancement

#600 Respect acre_sys_core_isDisabled
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_radio/fnc_canUnitReceive.sqf
  addons/sys_radio/fnc_canUnitTransmit.sqf
Labels: bug fix

#602 Fix shared radios in vehicles
  addons/sys_external/fnc_isExternalRadioAvailable.sqf
Labels: bug fix

#603 Bump CBA version requirement to v3.9.0
  addons/main/script_mod.hpp
Labels: task

#605 Fix typo in processVehicleSystemArray
  addons/sys_core/fnc_processVehicleSystemAccessArray.sqf
Labels: bug fix

#588 Expand argument checks in API functions
  addons/api/fnc_addRackToVehicle.sqf
  addons/api/fnc_areVehicleRacksInitialized.sqf
  addons/api/fnc_babelAddLanguageType.sqf
  addons/api/fnc_babelGetLanguageId.sqf
  addons/api/fnc_babelGetLanguageName.sqf
  addons/api/fnc_babelSetSpeakingLanguage.sqf
  addons/api/fnc_basicMissionSetup.sqf
  addons/api/fnc_copyPreset.sqf
  addons/api/fnc_getBaseRadio.sqf
  addons/api/fnc_getDisplayName.sqf
  addons/api/fnc_getMountedRackRadio.sqf
  addons/api/fnc_getPreset.sqf
  addons/api/fnc_getPresetChannelData.sqf
  addons/api/fnc_getPresetChannelField.sqf
  addons/api/fnc_getPresetData.sqf
  addons/api/fnc_getRadioByType.sqf
  addons/api/fnc_getRadioChannel.sqf
  addons/api/fnc_getRadioSpatial.sqf
  addons/api/fnc_getRadioVolume.sqf
  addons/api/fnc_getVehicleRacks.sqf
  addons/api/fnc_getVehicleRacksPreset.sqf
  addons/api/fnc_hasBaseRadio.sqf
  addons/api/fnc_hasKindOfRadio.sqf
  addons/api/fnc_hasRadio.sqf
  addons/api/fnc_initVehicleRacks.sqf
  addons/api/fnc_isBaseRadio.sqf
  addons/api/fnc_isBroadcasting.sqf
  addons/api/fnc_isInitialized.sqf
  addons/api/fnc_isKindOf.sqf
  addons/api/fnc_isRackRadioRemovable.sqf
  addons/api/fnc_isRadio.sqf
  addons/api/fnc_isSpeaking.sqf
  addons/api/fnc_isSpectator.sqf
  addons/api/fnc_mapChannelFieldName.sqf
  addons/api/fnc_mountRackRadio.sqf
  addons/api/fnc_removeRackFromVehicle.sqf
  addons/api/fnc_setCurrentRadio.sqf
  addons/api/fnc_setCurrentRadioChannelNumber.sqf
  addons/api/fnc_setCurveModel.sqf
  addons/api/fnc_setCurveModelScale.sqf
  addons/api/fnc_setDefaultChannels.sqf
  addons/api/fnc_setGlobalVolume.sqf
  addons/api/fnc_setMultiPushToTalkAssignment.sqf
  addons/api/fnc_setPTTDelay.sqf
  addons/api/fnc_setPreset.sqf
  addons/api/fnc_setPresetChannelField.sqf
  addons/api/fnc_setPresetData.sqf
  addons/api/fnc_setRadioChannel.sqf
  addons/api/fnc_setRadioSpatial.sqf
  addons/api/fnc_setRadioVolume.sqf
  addons/api/fnc_setSelectableVoiceCurve.sqf
  addons/api/fnc_setSpectator.sqf
  addons/api/fnc_setVehicleRacksPreset.sqf
  addons/api/fnc_setupMission.sqf
  addons/api/fnc_unmountRackRadio.sqf
Labels: enhancement
