Repository IDI-Systems/acre2, pull requests merged in 2018-03, with the labels that each got.

#500 Fix never displaying unmountable action
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/stringtable.xml
Labels: bug fix, trivial

#496 Intercom fixes
  addons/sys_core/fnc_processVehicleSystemAccessArray.sqf
  addons/sys_intercom/fnc_handleLimitedConnection.sqf
  addons/sys_intercom/fnc_setStationConfiguration.sqf
Labels: bug fix

#497 Enhance rack initialisation
  addons/api/fnc_addRackToVehicle.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/fnc_getPlayersInVehicle.sqf
  addons/sys_rack/fnc_enterVehicle.sqf
  addons/sys_rack/fnc_onReturnRackId.sqf
  addons/sys_rack/fnc_onReturnRadioId.sqf
Labels: enhancement

#503 Remove default keybinding
  addons/sys_intercom/XEH_postInit.sqf
Labels: cleanup

#501 Do not show the vehicle info display if no intercom or rack is available
  addons/sys_gui/XEH_postInit.sqf
Labels: bug fix, enhancement

#502 Polish translation
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation

#504 Fix babel mission setup
  addons/api/fnc_babelSetupMission.sqf
Labels: bug fix

#506 Fix frequency selection in 152 and 117f
  addons/sys_prc117f/CfgEventHandlers.hpp
  addons/sys_prc117f/farris_menus/PGM.sqf
  addons/sys_prc117f/fnc_formatChannelValue.sqf
  addons/sys_prc117f/menus/types/Frequency.sqf
  addons/sys_prc152/farris_menus/PGM.sqf
  addons/sys_prc152/fnc_formatChannelValue.sqf
  addons/sys_prc152/menus/types/Frequency.sqf
Labels: bug fix

#507 Fix pgm menu
  addons/sys_prc152/menus/types/ActionSeries.sqf
Labels: bug fix
