Repository IDI-Systems/acre2, pull requests merged in 2018-05, with the labels that each got.

#524 Signal Calculation Fix
  addons/sys_signal/fnc_getSignal.sqf
Labels: bug fix

#526 Improve Racks interaction usability
  addons/ace_interact/fnc_radioChildrenActions.sqf
  addons/sys_rack/CfgVehicles.hpp
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/fnc_rackListChildrenActions.sqf
  addons/sys_rack/stringtable.xml
  tools/sqf_validator.py
Labels: enhancement

#528 Fix Vehicle Info UI initialization
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_updateInfantryPhoneStatus.sqf
  addons/sys_rack/XEH_postInit.sqf
  addons/sys_rack/fnc_enterVehicle.sqf
Labels: bug fix, cleanup

#530 Fix documentation and intercom short name string length
  addons/sys_intercom/fnc_configIntercom.sqf
  docs/wiki/frameworks/vehicle-intercom.md
  docs/wiki/frameworks/vehicle-racks.md
Labels: documentation, enhancement

#532 Update Japanese translation
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation

#534 Allow rack initialisation based on a condition
  addons/api/CfgFunctions.hpp
  addons/api/fnc_addRackToVehicle.sqf
  addons/api/fnc_copyPreset.sqf
  addons/api/fnc_getVehicleRacksPreset.sqf
  addons/api/fnc_initVehicleRacks.sqf
  addons/api/fnc_setVehicleRacksPreset.sqf
  addons/sys_rack/fnc_onReturnRadioId.sqf
Labels: bug fix, needs testing

#537 Fix rack initialisation
  addons/api/fnc_addRackToVehicle.sqf
  addons/api/fnc_initVehicleRacks.sqf
  addons/sys_rack/fnc_onReturnRackId.sqf
  addons/sys_rack/fnc_onReturnRadioId.sqf
Labels: bug fix
