Repository IDI-Systems/acre2, pull requests merged in 2018-09, with the labels that each got.

#575 WIP: Port Hints to Notification System
  addons/sys_io/fnc_ping.sqf
  addons/sys_io/fnc_server.sqf
  addons/sys_io/fnc_serverReadLoop.sqf
  addons/sys_radio/fnc_handleRadioSpatialKeyPressed.sqf
Labels: enhancement

#581 Fix ACRE_BROADCASTING_RADIOID not syn. properly after using racks
  addons/sys_core/fnc_remoteStopSpeaking.sqf
Labels: bug fix

#584 Add babel code snippet for switching units of different side
  docs/wiki/frameworks/babel.md
Labels: documentation
