Repository IDI-Systems/acre2, pull requests merged in 2019-09, with the labels that each got.

#814 Add volume control color scale setting
  addons/sys_core/stringtable.xml
  addons/sys_gui/XEH_preInit.sqf
  addons/sys_gui/fnc_getVolumeColor.sqf
  addons/sys_gui/initSettings.sqf
  addons/sys_gui/script_component.hpp
  addons/sys_gui/stringtable.xml
  addons/sys_list/initSettings.sqf
  addons/sys_list/stringtable.xml
Labels: feature request

#822 Use Slack badge from shields.io
  README.md
  docs/_data/topnav.yml
Labels: ignore changelog, task

#808 Document mod configuration (CBA Settings)
  docs/wiki/user/installation.md
Labels: documentation

#823 Change Todo to Enhancement template
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/todo.md
Labels: ignore changelog, tools

#824 Russian Localization Update
  addons/ace_interact/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_signal/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#802 Open Intercom UI from main interaction point
  addons/sys_intercom/fnc_intercomChildrenActions.sqf
Labels: enhancement

#825 Use CBA Versioning System properly
  addons/main/script_mod.hpp
  tools/cba/addons/main/script_macros_common.hpp
Labels: enhancement, task

#828 Variable redefinition in LOS Multipath
  extensions/src/ACRE2Arma/signal/models/los_simple.cpp
Labels: bug fix

#832 Fix double Arsenal radios
  addons/sys_data/fnc_getPlayerRadioList.sqf
Labels: bug fix

#840 Fix updateIntercomUse function
  addons/sys_intercom/fnc_intercomPFH.sqf
  addons/sys_intercom/fnc_updateIntercomUse.sqf
Labels: bug fix

#839 Return proper volume in API function.
  addons/api/fnc_getRadioVolume.sqf
Labels: bug fix

#841 Do not connect intercom automatically if no access to it is possible
  addons/sys_intercom/fnc_configIntercomStations.sqf
Labels: bug fix

#842 Do not show intercoms that are not accessbile in the info panel
  addons/sys_intercom/fnc_updateVehicleInfoText.sqf
Labels: bug fix

#843 Show vehicle info UI when entering in a seat without access to the first intercom
  addons/sys_gui/XEH_postInit.sqf
Labels: bug fix

#844 Do not auto connect limited positions
  addons/sys_intercom/fnc_configIntercomStations.sqf
Labels: bug fix
