Repository IDI-Systems/acre2, pull requests merged in 2019-03, with the labels that each got.

#634 Allow Helicopter 'Gunner' Copilot to access racks
  addons/sys_rack/CfgVehicles.hpp
Labels: enhancement

#642 Change default radio keys and streamline key strings
  addons/ace_interact/stringtable.xml
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/stringtable.xml
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/stringtable.xml
  addons/sys_list/XEH_postInit.sqf
  addons/sys_list/stringtable.xml
Labels: enhancement

#644 Support for other signal models
  addons/sys_signal/XEH_preInit.sqf
  addons/sys_signal/fnc_getSignal.sqf
  addons/sys_signal/initSettings.sqf
  addons/sys_signal/script_component.hpp
  addons/sys_signal/stringtable.xml
  extensions/src/ACRE2Arma/signal/antenna/antenna.cpp
  extensions/src/ACRE2Arma/signal/antenna/antenna.hpp
  extensions/src/ACRE2Arma/signal/map/map.cpp
  extensions/src/ACRE2Arma/signal/map/map.hpp
  extensions/src/ACRE2Arma/signal/models/Arcade.cpp
  extensions/src/ACRE2Arma/signal/models/Arcade.hpp
  extensions/src/ACRE2Arma/signal/models/los_simple.cpp
  extensions/src/ACRE2Arma/signal/models/los_simple.hpp
  extensions/src/ACRE2Arma/signal/models/models_common.hpp
  extensions/src/ACRE2Arma/signal/signal.hpp
Labels: enhancement

#649 All clients should have the same propagation model.
  addons/sys_signal/initSettings.sqf
Labels: bug fix

#650 Add debug for dev-build
  addons/sys_signal/fnc_handleSignalReturn.sqf
  addons/sys_signal/script_component.hpp
Labels: cleanup, debug, ignore changelog
