Repository IDI-Systems/acre2, pull requests merged in 2019-06, with the labels that each got.

#678 TS plugin copy: Cleanup and fixes.
  extensions/src/ACRE2Steam/CallExt_DllMain.cpp
Labels: cleanup, enhancement

#680 SEM70 - Fix UI not scaling properly
  addons/sys_sem70/sem70_RadioDialog.hpp
Labels: bug fix

#675 Fixes to intercom
  addons/sys_intercom/fnc_openGui.sqf
  addons/sys_intercom/vic3/fnc_vic3ffcsConfig.sqf
  addons/sys_intercom/vic3/fnc_vic3ffcsOnVolumeKnobPress.sqf
  addons/sys_intercom/vic3/vic3_ffcs_intercomDialog.hpp
Labels: bug fix

#676 Use CBA_fnc_notify
  addons/sys_components/fnc_toggleAntennaDir.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/fnc_switchRadioEar.sqf
  addons/sys_core/fnc_toggleHeadset.sqf
  addons/sys_external/XEH_postInit.sqf
  addons/sys_external/fnc_startUsingExternalRadio.sqf
  addons/sys_external/fnc_stopUsingExternalRadio.sqf
  addons/sys_gsa/XEH_postInit.sqf
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_handleLimitedConnection.sqf
  addons/sys_intercom/fnc_setStationConfiguration.sqf
  addons/sys_intercom/fnc_updateInfantryPhoneStatus.sqf
  addons/sys_intercom/stringtable.xml
  addons/sys_io/fnc_ping.sqf
  addons/sys_io/fnc_server.sqf
  addons/sys_io/fnc_serverReadLoop.sqf
  addons/sys_io/stringtable.xml
  addons/sys_rack/fnc_unmountRadio.sqf
  addons/sys_radio/fnc_canOpenRadio.sqf
  addons/sys_radio/fnc_canUnitTransmit.sqf
  addons/sys_radio/fnc_handleRadioSpatialKeyPressed.sqf
  addons/sys_radio/stringtable.xml
  addons/sys_server/fnc_openRadioCheckResult.sqf
Labels: bug fix, enhancement

#690 Fix ACE interact menu bad path for ACRE_ZeusEars
  addons/sys_zeus/XEH_postInit.sqf
Labels: bug fix

#694 Add TeamSpeak API v23 (and older) compatibility
  extensions/src/ACRE2DistortionTestPlugin/CMakeLists.txt
  extensions/src/ACRE2DistortionTestPlugin/TSCallbacks_init.cpp
  extensions/src/ACRE2DistortionTestPlugin/TsCallbacks.h
  extensions/src/ACRE2DistortionTestPlugin/TsCallbacks_pluginEvents.cpp
  extensions/src/ACRE2DistortionTestPlugin/api_compat.asm
  extensions/src/ACRE2DistortionTestPlugin/inc/teamspeak/clientlib_publicdefinitions.h
  extensions/src/ACRE2DistortionTestPlugin/inc/teamspeak/public_definitions.h
  extensions/src/ACRE2DistortionTestPlugin/inc/teamspeak/public_errors.h
  extensions/src/ACRE2DistortionTestPlugin/inc/teamspeak/public_errors_rare.h
  extensions/src/ACRE2DistortionTestPlugin/inc/teamspeak/public_rare_definitions.h
  extensions/src/ACRE2DistortionTestPlugin/inc/ts3_functions.h
  extensions/src/ACRE2Shared/_CONSTANTS.h
  extensions/src/ACRE2Shared/helpers.cpp
  extensions/src/ACRE2Shared/helpers.h
  extensions/src/ACRE2TS/CMakeLists.txt
  extensions/src/ACRE2TS/TSCallbacks_init.cpp
  extensions/src/ACRE2TS/TsCallbacks.h
  extensions/src/ACRE2TS/TsCallbacks_channelEvents.cpp
  extensions/src/ACRE2TS/TsCallbacks_pluginEvents.cpp
  extensions/src/ACRE2TS/TsCallbacks_sound.cpp
  extensions/src/ACRE2TS/TsCallbacks_speaking.cpp
  extensions/src/ACRE2TS/TsFunctions.h
  extensions/src/ACRE2TS/api_compat.asm
  extensions/src/ACRE2TS/inc/public_errors.h
  extensions/src/ACRE2TS/inc/public_errors_rare.h
  extensions/src/ACRE2TS/inc/teamspeak/clientlib_publicdefinitions.h
  extensions/src/ACRE2TS/inc/teamspeak/public_definitions.h
  extensions/src/ACRE2TS/inc/teamspeak/public_errors.h
  extensions/src/ACRE2TS/inc/teamspeak/public_errors_rare.h
  extensions/src/ACRE2TS/inc/teamspeak/public_rare_definitions.h
  extensions/src/ACRE2TS/inc/ts3_functions.h
Labels: TeamSpeak's fault, compatibility, to-cherrypick

#693 Fixes to Rack/Intercom ACE actions
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_closeGui.sqf
  addons/sys_intercom/fnc_handleLimitedConnection.sqf
  addons/sys_intercom/fnc_openGui.sqf
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/fnc_rackListChildrenActions.sqf
Labels: bug fix

#695 Fix Zeus keybind error
  addons/sys_zeus/fnc_handleZeusSpeakPress.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPressUp.sqf
Labels: bug fix

#696 Remove redundant TeamSpeak API v23 compatibility function
  extensions/src/ACRE2DistortionTestPlugin/TsCallbacks.h
  extensions/src/ACRE2TS/TsCallbacks.h
Labels: cleanup

#699 Fix Intercom when monitoring all racks
  addons/sys_intercom/vic3/fnc_vic3ffcsOnWorkKnobPress.sqf
Labels: bug fix, needs testing
