Repository IDI-Systems/acre2, pull requests merged in 2019-07, with the labels that each got.

#701 Fix cba prestart func optimization
  addons/sys_external/CfgEventHandlers.hpp
  addons/sys_signalmap/CfgEventHandlers.hpp
Labels: bug fix, trivial

#700 Improve TeamSpeak connection notifications scale
  addons/sys_io/fnc_server.sqf
Labels: enhancement

#702 Fix unit not being properly removed when disconnecting intercom
  addons/sys_intercom/fnc_setStationConfiguration.sqf
Labels: bug fix

#705 Pass on PRC77
  addons/sys_prc77/functions/fnc_onBandSelectorKnobPress.sqf
  addons/sys_prc77/functions/fnc_onFunctionKnobPress.sqf
  addons/sys_prc77/functions/fnc_onMHzTuneKnobPress.sqf
  addons/sys_prc77/functions/fnc_onkHzTuneKnobPress.sqf
  addons/sys_prc77/functions/fnc_snapbackFunctionKnob.sqf
  addons/sys_prc77/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc77/radio/fnc_handleEndTransmission.sqf
  addons/sys_prc77/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_prc77/radio/fnc_handlePTTDown.sqf
  addons/sys_prc77/radio/fnc_handlePTTUp.sqf
  addons/sys_prc77/radio/fnc_openGui.sqf
Labels: cleanup, optimization

#706 Pass on SEM52SL
  addons/sys_sem52sl/functions/fnc_renderDisplay.sqf
  addons/sys_sem52sl/radio/fnc_getChannelData.sqf
  addons/sys_sem52sl/radio/fnc_getChannelDescription.sqf
  addons/sys_sem52sl/radio/fnc_getCurrentChannel.sqf
  addons/sys_sem52sl/radio/fnc_getCurrentChannelData.sqf
  addons/sys_sem52sl/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_sem52sl/radio/fnc_getOnOffState.sqf
  addons/sys_sem52sl/radio/fnc_getSpatial.sqf
  addons/sys_sem52sl/radio/fnc_getState.sqf
  addons/sys_sem52sl/radio/fnc_getStates.sqf
  addons/sys_sem52sl/radio/fnc_getVolume.sqf
  addons/sys_sem52sl/radio/fnc_handleBeginTransmission.sqf
  addons/sys_sem52sl/radio/fnc_handleEndTransmission.sqf
  addons/sys_sem52sl/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_sem52sl/radio/fnc_handlePTTDown.sqf
  addons/sys_sem52sl/radio/fnc_handlePTTUp.sqf
  addons/sys_sem52sl/radio/fnc_initializeRadio.sqf
  addons/sys_sem52sl/radio/fnc_isExternalAudio.sqf
  addons/sys_sem52sl/radio/fnc_openGui.sqf
  addons/sys_sem52sl/radio/fnc_setChannelData.sqf
  addons/sys_sem52sl/radio/fnc_setCurrentChannel.sqf
  addons/sys_sem52sl/radio/fnc_setOnOffState.sqf
  addons/sys_sem52sl/radio/fnc_setSpatial.sqf
  addons/sys_sem52sl/radio/fnc_setState.sqf
  addons/sys_sem52sl/radio/fnc_setVolume.sqf
Labels: cleanup, optimization

#707 Pass on SEM70
  addons/sys_sem70/functions/fnc_clearDisplay.sqf
  addons/sys_sem70/functions/fnc_render.sqf
  addons/sys_sem70/functions/fnc_renderDisplay.sqf
  addons/sys_sem70/functions/fnc_setNetworkID.sqf
  addons/sys_sem70/radio/fnc_getChannelData.sqf
  addons/sys_sem70/radio/fnc_getChannelDescription.sqf
  addons/sys_sem70/radio/fnc_getCurrentChannel.sqf
  addons/sys_sem70/radio/fnc_getCurrentChannelData.sqf
  addons/sys_sem70/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_sem70/radio/fnc_getOnOffState.sqf
  addons/sys_sem70/radio/fnc_getSpatial.sqf
  addons/sys_sem70/radio/fnc_getState.sqf
  addons/sys_sem70/radio/fnc_getStates.sqf
  addons/sys_sem70/radio/fnc_getVolume.sqf
  addons/sys_sem70/radio/fnc_handleBeginTransmission.sqf
  addons/sys_sem70/radio/fnc_handleEndTransmission.sqf
  addons/sys_sem70/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_sem70/radio/fnc_handlePTTDown.sqf
  addons/sys_sem70/radio/fnc_handlePTTUp.sqf
  addons/sys_sem70/radio/fnc_handleSignalData.sqf
  addons/sys_sem70/radio/fnc_initializeRadio.sqf
  addons/sys_sem70/radio/fnc_isExternalAudio.sqf
  addons/sys_sem70/radio/fnc_openGui.sqf
  addons/sys_sem70/radio/fnc_setChannelData.sqf
  addons/sys_sem70/radio/fnc_setCurrentChannel.sqf
  addons/sys_sem70/radio/fnc_setOnOffState.sqf
  addons/sys_sem70/radio/fnc_setSpatial.sqf
  addons/sys_sem70/radio/fnc_setState.sqf
  addons/sys_sem70/radio/fnc_setVolume.sqf
Labels: cleanup, optimization

#704 Pass on PRC117F
  addons/sys_prc117f/fnc_formatChannelValue.sqf
  addons/sys_prc117f/fnc_openGui.sqf
  addons/sys_prc117f/fnc_preset_information.sqf
  addons/sys_prc117f/fnc_render.sqf
  addons/sys_prc117f/menus/fnc_callButtonFunctor.sqf
  addons/sys_prc117f/menus/fnc_callCompleteFunctor.sqf
  addons/sys_prc117f/menus/fnc_callEntryFunctor.sqf
  addons/sys_prc117f/menus/fnc_callRenderFunctor.sqf
  addons/sys_prc117f/menus/fnc_callSingleActionCompleteFunctor.sqf
  addons/sys_prc117f/menus/fnc_changeMenu.sqf
  addons/sys_prc117f/menus/fnc_changeValueAck.sqf
  addons/sys_prc117f/menus/fnc_createMenu.sqf
  addons/sys_prc117f/menus/fnc_delayFunction.sqf
  addons/sys_prc117f/menus/fnc_drawCursor.sqf
  addons/sys_prc117f/menus/fnc_dynamicCall.sqf
  addons/sys_prc117f/menus/fnc_formatText.sqf
  addons/sys_prc117f/menus/fnc_onButtonPress.sqf
  addons/sys_prc117f/menus/fnc_timerFunction.sqf
  addons/sys_prc117f/menus/fnc_toggleButtonPressDown.sqf
  addons/sys_prc117f/menus/fnc_toggleButtonPressUp.sqf
  addons/sys_prc117f/radio/fnc_getChannelData.sqf
  addons/sys_prc117f/radio/fnc_getChannelDataInternal.sqf
  addons/sys_prc117f/radio/fnc_getCurrentChannel.sqf
  addons/sys_prc117f/radio/fnc_getCurrentChannelData.sqf
  addons/sys_prc117f/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc117f/radio/fnc_getOnOffState.sqf
  addons/sys_prc117f/radio/fnc_getState.sqf
  addons/sys_prc117f/radio/fnc_getVolume.sqf
  addons/sys_prc117f/radio/fnc_handleBeginTransmission.sqf
  addons/sys_prc117f/radio/fnc_handleEndTransmission.sqf
  addons/sys_prc117f/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_prc117f/radio/fnc_handlePTTDown.sqf
  addons/sys_prc117f/radio/fnc_handlePTTUp.sqf
  addons/sys_prc117f/radio/fnc_setChannelDataOperational.sqf
  addons/sys_prc117f/radio/fnc_setCurrentChannel.sqf
  addons/sys_prc117f/radio/fnc_setOnOffState.sqf
  addons/sys_prc117f/radio/fnc_setSpatial.sqf
  addons/sys_prc117f/radio/fnc_setState.sqf
  addons/sys_prc117f/radio/fnc_setVolume.sqf
Labels: cleanup, optimization

#703 Pass on PRC152
  addons/sys_prc152/fnc_formatChannelValue.sqf
  addons/sys_prc152/fnc_openGui.sqf
  addons/sys_prc152/fnc_preset_information.sqf
  addons/sys_prc152/fnc_render.sqf
  addons/sys_prc152/menus/fnc_callButtonFunctor.sqf
  addons/sys_prc152/menus/fnc_callCompleteFunctor.sqf
  addons/sys_prc152/menus/fnc_callEntryFunctor.sqf
  addons/sys_prc152/menus/fnc_callRenderFunctor.sqf
  addons/sys_prc152/menus/fnc_callSingleActionCompleteFunctor.sqf
  addons/sys_prc152/menus/fnc_changeMenu.sqf
  addons/sys_prc152/menus/fnc_changeMode.sqf
  addons/sys_prc152/menus/fnc_changeValueAck.sqf
  addons/sys_prc152/menus/fnc_createMenu.sqf
  addons/sys_prc152/menus/fnc_drawCursor.sqf
  addons/sys_prc152/menus/fnc_formatText.sqf
  addons/sys_prc152/menus/fnc_onButtonPress.sqf
  addons/sys_prc152/menus/fnc_timerFunction.sqf
  addons/sys_prc152/menus/fnc_toggleButtonPressDown.sqf
  addons/sys_prc152/menus/fnc_toggleButtonPressUp.sqf
  addons/sys_prc152/menus/fnc_toggleIcon.sqf
  addons/sys_prc152/menus/fnc_verifyIsMenu.sqf
  addons/sys_prc152/radio/fnc_getChannelDataInternal.sqf
  addons/sys_prc152/radio/fnc_getCurrentChannel.sqf
  addons/sys_prc152/radio/fnc_getCurrentChannelData.sqf
  addons/sys_prc152/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc152/radio/fnc_getState.sqf
  addons/sys_prc152/radio/fnc_getVolume.sqf
  addons/sys_prc152/radio/fnc_handleBeginTransmission.sqf
  addons/sys_prc152/radio/fnc_handleEndTransmission.sqf
  addons/sys_prc152/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_prc152/radio/fnc_handlePTTDown.sqf
  addons/sys_prc152/radio/fnc_handlePTTUp.sqf
  addons/sys_prc152/radio/fnc_isExternalAudio.sqf
  addons/sys_prc152/radio/fnc_setOnOffState.sqf
  addons/sys_prc152/radio/fnc_setSpatial.sqf
  addons/sys_prc152/radio/fnc_setState.sqf
  addons/sys_prc152/radio/fnc_setVolume.sqf
Labels: cleanup, optimization

#708 Fix rack initialisation
  addons/sys_intercom/fnc_configRackRxTxCapabilities.sqf
Labels: bug fix

#709 Do not show Rack icon if there are no racks
  addons/sys_rack/fnc_initActionVehicle.sqf
Labels: bug fix

#641 Move antenna parsing to preStart
  addons/sys_antenna/CfgEventHandlers.hpp
  addons/sys_antenna/XEH_postInit.sqf
  addons/sys_antenna/XEH_preStart.sqf
  addons/sys_antenna/config.cpp
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/XEH_preStart.sqf
Labels: enhancement

#714 Use Arma 3 Load Order for vanilla requiredAddons
  addons/main/config.cpp
Labels: cleanup

#713 Remove old version display
  addons/main/CfgRscStd.hpp
  addons/main/config.cpp
Labels: cleanup

#716 Fix GSA bugs
  addons/sys_gsa/CfgVehicles.hpp
  addons/sys_gsa/XEH_PREP.hpp
  addons/sys_gsa/XEH_postInit.sqf
  addons/sys_gsa/fnc_disconnect.sqf
  addons/sys_gsa/fnc_hasCompatibleRadios.sqf
  addons/sys_gsa/fnc_pickUp.sqf
  addons/sys_gsa/stringtable.xml
Labels: bug fix, enhancement

#718 Fix connector interact options incorrect usage of attachComplexComponent
  addons/ace_interact/fnc_generateConnectorActions.sqf
  addons/sys_components/fnc_attachComplexComponent.sqf
  addons/sys_components/fnc_attachSimpleComponent.sqf
Labels: bug fix, ignore changelog

#720 Remove dev-build comments
  docs/wiki/user/radio-signal-loss.md
  docs/wiki/user/ts-channel-switching.md
  docs/wiki/user/vehicle-intercom.md
Labels: documentation, ignore changelog

#724 Set default Intercom UI key to Ctrl+Shift+Tab
  addons/sys_intercom/XEH_postInit.sqf
Labels: ignore changelog, task

#715 Update Load Order for 1.94 Contact DLC
  addons/main/config.cpp
  addons/main/script_mod.hpp
Labels: task, trivial

#717 Convert acre::Vector3 to a template
  extensions/src/ACRE2Core/Player.h
  extensions/src/ACRE2Core/SoundPlayback.cpp
  extensions/src/ACRE2Core/SoundPlayback.h
  extensions/src/ACRE2Core/playSound.h
  extensions/src/ACRE2Core/updateSelf.h
  extensions/src/ACRE2DistortionTestPlugin/TS3Client.cpp
  extensions/src/ACRE2DistortionTestPlugin/TS3Client.h
  extensions/src/ACRE2Shared/ACRE_VECTOR.h
  extensions/src/ACRE2Shared/IClient.h
  extensions/src/ACRE2TS/TS3Client.cpp
  extensions/src/ACRE2TS/TS3Client.h
Labels: enhancement

#736 Use the bent antenna icon when prone or crouch in automatic mode
  addons/sys_gui/fnc_antennaElevationDisplay.sqf
Labels: bug fix, enhancement

#722 Spatial display
  addons/sys_core/fnc_showBroadCastHint.sqf
  addons/sys_list/fnc_displayHint.sqf
Labels: enhancement
