Repository IDI-Systems/acre2, pull requests merged in 2019-08, with the labels that each got.

#737 Fix badly formatted translation
  addons/sys_io/stringtable.xml
Labels: bug fix, ignore changelog

#733 Adjust description when plugin failed to be copied to match button name
  extensions/src/ACRE2Steam/CallExt_DllMain.cpp
Labels: ignore changelog, trivial

#723 Mass replace __inline with inline
  extensions/src/ACRE2Core/NamedPipeServer.h
  extensions/src/ACRE2Core/ext_handleGetClientID.h
  extensions/src/ACRE2Core/ext_remoteStartSpeaking.h
  extensions/src/ACRE2Core/ext_remoteStopSpeaking.h
  extensions/src/ACRE2Core/ext_reset.h
  extensions/src/ACRE2Core/getClientID.h
  extensions/src/ACRE2Core/getPluginVersion.h
  extensions/src/ACRE2Core/loadSound.h
  extensions/src/ACRE2Core/localMute.h
  extensions/src/ACRE2Core/ping.h
  extensions/src/ACRE2Core/playSound.h
  extensions/src/ACRE2Core/setMuted.h
  extensions/src/ACRE2Core/setPTTKeys.h
  extensions/src/ACRE2Core/setSelectableVoiceCurve.h
  extensions/src/ACRE2Core/setSetting.h
  extensions/src/ACRE2Core/setSoundSystemMasterOverride.h
  extensions/src/ACRE2Core/setTs3ChannelDetails.h
  extensions/src/ACRE2Core/setVoiceCurveModel.h
  extensions/src/ACRE2Core/startIntercomSpeaking.h
  extensions/src/ACRE2Core/startRadioSpeaking.h
  extensions/src/ACRE2Core/stopIntercomSpeaking.h
  extensions/src/ACRE2Core/stopRadioSpeaking.h
  extensions/src/ACRE2Core/updateSelf.h
  extensions/src/ACRE2Core/updateSpeakingData.h
  extensions/src/ACRE2DistortionTestPlugin/CommandServer.h
  extensions/src/ACRE2DistortionTestPlugin/TS3Client.h
  extensions/src/ACRE2Shared/EntrantWorker.h
  extensions/src/ACRE2Shared/Macros.h
  extensions/src/ACRE2TS/CommandServer.h
  extensions/src/ACRE2TS/TS3Client.h
Labels: cleanup

#751 Disconnect aircraft radios from intercoms
  addons/sys_rack/CfgVehicles.hpp
Labels: enhancement

#752 Use CBA_fnc_addSetting
  addons/sys_core/initSettings.sqf
  addons/sys_rack/fnc_attachComponent.sqf
  addons/sys_signal/initSettings.sqf
Labels: enhancement

#757 Disable MSVC unused safe (*_s) function warnings
  extensions/CMakeModules/cxx_compiler_functions.cmake
Labels: enhancement, ignore changelog, tools

#754 Add ACE3 requirement note to Vehicle Intercom documentation
  docs/wiki/frameworks/vehicle-intercom.md
  docs/wiki/frameworks/vehicle-racks.md
  docs/wiki/user/vehicle-intercom.md
Labels: documentation, ignore changelog

#748 Update development environment requirements
  docs/wiki/development/building.md
Labels: documentation, ignore changelog, tools

#745 Zeus - Communicate
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPress.sqf
  addons/sys_zeus/initSettings.sqf
  addons/sys_zeus/stringtable.xml
Labels: enhancement

#719 Use tags for TS metadata
  extensions/CMakeLists.txt
  extensions/CMakeModules/cxx_compiler_functions.cmake
  extensions/src/ACRE2Arma/CMakeLists.txt
  extensions/src/ACRE2Arma/common/glm/detail/setup.hpp
  extensions/src/ACRE2Arma/common/glm/gtx/range.hpp
  extensions/src/ACRE2Arma/common/glm/gtx/scalar_multiplication.hpp
  extensions/src/ACRE2DistortionTestPlugin/TsCallbacks_static.cpp
  extensions/src/ACRE2TS/CMakeLists.txt
  extensions/src/ACRE2TS/TS3Client.cpp
  extensions/src/ACRE2TS/TS3Client.h
  extensions/src/ACRE2TS/TsCallbacks_static.cpp
  extensions/src/ACRE2TS/inc/plugin_definitions.h
  extensions/vcproj64/.gitignore
Labels: enhancement

#755 Cleanup config of Racks and Intercom
  addons/sys_intercom/CfgVehicles.hpp
  addons/sys_rack/CfgVehicles.hpp
  docs/wiki/frameworks/vehicle-intercom.md
  docs/wiki/frameworks/vehicle-racks.md
Labels: cleanup

#753 Support infantry phone on very large vehicles
  addons/sys_intercom/fnc_infantryPhoneAction.sqf
  addons/sys_intercom/script_component.hpp
  addons/sys_signal/fnc_handleSignalReturn.sqf
  addons/sys_signal/script_component.hpp
Labels: enhancement, needs testing

#731 Default radio volume
  addons/sys_core/initSettings.sqf
  addons/sys_core/stringtable.xml
  addons/sys_prc117f/fnc_initializeRadio.sqf
  addons/sys_prc148/fnc_initializeRadio.sqf
  addons/sys_prc152/fnc_initializeRadio.sqf
  addons/sys_prc343/radio/fnc_initializeRadio.sqf
  addons/sys_prc77/radio/fnc_initializeRadio.sqf
  addons/sys_sem52sl/radio/fnc_initializeRadio.sqf
  addons/sys_sem70/radio/fnc_initializeRadio.sqf
Labels: feature request

#761 Fix and improve Intercom and Rack configuration warnings
  addons/sys_intercom/fnc_configInfantryPhone.sqf
  addons/sys_intercom/fnc_configIntercom.sqf
  addons/sys_rack/fnc_configWiredIntercoms.sqf
  addons/sys_rack/fnc_initVehicle.sqf
Labels: bug fix, enhancement

#764 Fix and improve Vehicle Info UI for 1.94
  addons/sys_gui/CfgRscTitles.hpp
  addons/sys_gui/CfgUIGrids.hpp
  addons/sys_gui/script_component.hpp
  addons/sys_list/CfgUIGrids.hpp
Labels: bug fix, enhancement

#759 Support reserved keys in radio and intercom dialogs
  addons/sys_intercom/fnc_openGui.sqf
  addons/sys_intercom/script_component.hpp
  addons/sys_intercom/vic3/script_component.hpp
  addons/sys_list/XEH_postInit.sqf
  addons/sys_prc117f/fnc_openGui.sqf
  addons/sys_prc148/fnc_openGui.sqf
  addons/sys_prc152/fnc_openGui.sqf
  addons/sys_prc343/radio/fnc_openGui.sqf
  addons/sys_prc77/radio/fnc_openGui.sqf
  addons/sys_sem52sl/radio/fnc_openGui.sqf
  addons/sys_sem70/radio/fnc_openGui.sqf
  docs/wiki/user/vehicle-intercom.md
Labels: bug fix, cleanup, enhancement

#767 Fix ITM adiff function
  extensions/src/ACRE2Arma/signal/models/longleyRice_itm.cpp
Labels: bug fix

#766 Make ITM/ITWOM thread safe
  extensions/src/ACRE2Arma/signal/models/longleyRice_itm.cpp
  extensions/src/ACRE2Arma/signal/models/longleyRice_itwom3.0.cpp
Labels: enhancement

#738 Rewrite volume control
  addons/api/XEH_preInit.sqf
  addons/api/fnc_setSelectableVoiceCurve.sqf
  addons/sys_core/fnc_coreInitPFH.sqf
  addons/sys_core/fnc_localStartSpeaking.sqf
  addons/sys_core/fnc_localStopSpeaking.sqf
  addons/sys_gui/CfgEventHandlers.hpp
  addons/sys_gui/CfgUIGrids.hpp
  addons/sys_gui/MyDialogDefines.hpp
  addons/sys_gui/RscInGameUI.hpp
  addons/sys_gui/RscTitles.hpp
  addons/sys_gui/XEH_PREP.hpp
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_gui/XEH_preInit.sqf
  addons/sys_gui/config.cpp
  addons/sys_gui/data/ui/volume_control_preview.paa
  addons/sys_gui/fnc_closeVolumeControl.sqf
  addons/sys_gui/fnc_getVolumeColor.sqf
  addons/sys_gui/fnc_missionDisplayLoad.sqf
  addons/sys_gui/fnc_onMouseZChanged.sqf
  addons/sys_gui/fnc_onVolumeControlAdjust.sqf
  addons/sys_gui/fnc_onVolumeControlKeyPress.sqf
  addons/sys_gui/fnc_onVolumeControlKeyPressUp.sqf
  addons/sys_gui/fnc_onVolumeControlSliderChanged.sqf
  addons/sys_gui/fnc_openVolumeControl.sqf
  addons/sys_gui/fnc_setVoiceCurveLevel.sqf
  addons/sys_gui/fnc_setVolumeSliderColor.sqf
  addons/sys_gui/fnc_volumeKeyDown.sqf
  addons/sys_gui/fnc_volumeKeyUp.sqf
  addons/sys_gui/script_component.hpp
  addons/sys_gui/script_strings.hpp
  addons/sys_gui/stringtable.xml
Labels: cleanup, enhancement

#770 Fix SEM70 heareable transmissions
  addons/sys_sem70/radio/fnc_handleMultipleTransmissions.sqf
Labels: bug fix

#769 Fix SEM52SL heareable transmissions
  addons/sys_sem52sl/radio/fnc_handleMultipleTransmissions.sqf
Labels: bug fix

#768 Small changes to signal addon
  addons/sys_signal/fnc_getSignal.sqf
  addons/sys_signal/fnc_handleSignalReturn.sqf
Labels: enhancement

#775 Small optimisation in sys_rpc
  addons/sys_rpc/fnc_callRemoteProcedure.sqf
Labels: optimization

#777 Allow some notifications to be skipped
  addons/sys_components/fnc_toggleAntennaDir.sqf
  addons/sys_core/fnc_switchRadioEar.sqf
  addons/sys_core/fnc_toggleHeadset.sqf
  addons/sys_external/XEH_postInit.sqf
  addons/sys_external/fnc_startUsingExternalRadio.sqf
  addons/sys_external/fnc_stopUsingExternalRadio.sqf
  addons/sys_intercom/fnc_updateInfantryPhoneStatus.sqf
  addons/sys_radio/fnc_handleRadioSpatialKeyPressed.sqf
  addons/sys_server/fnc_openRadioCheckResult.sqf
Labels: enhancement

#776 Small optimisations on sys_io
  addons/sys_io/fnc_missionDisplayLoad.sqf
  addons/sys_io/fnc_ping.sqf
  addons/sys_io/fnc_serverReadLoop.sqf
Labels: optimization

#773 Convert GVAR(lowered) to bool
  addons/ace_interact/fnc_radioListChildrenActions.sqf
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_core/fnc_toggleHeadset.sqf
Labels: optimization

#778 Streamline Open Intercom GUI key name
  addons/sys_intercom/stringtable.xml
Labels: enhancement

#771 Fix Intercom Work Knob
  addons/sys_intercom/vic3/fnc_vic3ffcsOnWorkKnobPress.sqf
Labels: bug fix

#772 Remove some obsolete comments in sys_core
  addons/sys_core/config.cpp
  addons/sys_core/fnc_getClientIdLoop.sqf
  addons/sys_core/fnc_getCompartment.sqf
  addons/sys_core/fnc_handleMultiPttKeyPress.sqf
  addons/sys_core/fnc_handleMultiPttKeyPressUp.sqf
  addons/sys_core/fnc_muting.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_processRadioSpeaker.sqf
  addons/sys_core/fnc_removeGear.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_core/fnc_spectatorOff.sqf
  addons/sys_core/fnc_spectatorOn.sqf
Labels: cleanup, ignore changelog

#774 Optimisations in sys_mode
  addons/sys_modes/fnc_checkAvailability.sqf
  addons/sys_modes/fnc_sc_muting.sqf
  addons/sys_modes/fnc_sc_speaking.sqf
  addons/sys_modes/fnc_sem70akw_muting.sqf
  addons/sys_modes/fnc_sem70akw_speaking.sqf
Labels: cleanup, optimization

#780 Fix Vehicle Info UI text cut-off and apply retroactive fix
  addons/sys_gui/CfgUIGrids.hpp
  addons/sys_gui/RscTitles.hpp
  addons/sys_intercom/stringtable.xml
Labels: bug fix

#782 Fix zeus position
  addons/sys_core/fnc_inRange.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
Labels: bug fix

#781 Hide infantry phone action when ringing is disabled
  addons/sys_intercom/fnc_handlePttKeyPress.sqf
  addons/sys_intercom/fnc_infantryPhoneAction.sqf
  addons/sys_intercom/fnc_infantryPhoneChildrenActions.sqf
Labels: bug fix

#783 No racks in near radios
  addons/sys_components/CfgAcreComponents.hpp
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_radio/fnc_nearRadios.sqf
Labels: enhancement

#784 GSA: CBA events have their own functions
  addons/sys_gsa/XEH_PREP.hpp
  addons/sys_gsa/XEH_postInit.sqf
  addons/sys_gsa/fnc_connectServer.sqf
  addons/sys_gsa/fnc_disconnectServer.sqf
Labels: cleanup

#787 Revert terrain loss coefficient at 1.0 default
  addons/sys_core/initSettings.sqf
Labels: enhancement

#760 Display frequency on single-channel radios in ACE Interact
  addons/ace_interact/fnc_radioListChildrenActions.sqf
  addons/api/fnc_getRadioChannel.sqf
Labels: enhancement

#729 Hint UI Customization
  addons/main/script_macros.hpp
  addons/sys_core/fnc_cycleLanguage.sqf
  addons/sys_core/fnc_showBroadCastHint.sqf
  addons/sys_core/fnc_switchChannelFast.sqf
  addons/sys_core/fnc_toggleHeadset.sqf
  addons/sys_list/XEH_preInit.sqf
  addons/sys_list/fnc_cycleRadios.sqf
  addons/sys_list/fnc_showHintBox.sqf
  addons/sys_list/initSettings.sqf
  addons/sys_list/stringtable.xml
Labels: feature request

#788 Correct config warning for rack short name length
  addons/sys_rack/fnc_initVehicle.sqf
Labels: enhancement

#789 Typo in variable name: PRC77
  addons/sys_prc77/radio/fnc_handleEndTransmission.sqf
Labels: bug fix

#791 Fix racks not being properly added to intercom in MP
  addons/sys_intercom/fnc_configRackRxTxCapabilities.sqf
Labels: bug fix

#793 Fucking stupid underscore
  addons/sys_modes/fnc_sc_muting.sqf
Labels: bug fix

#796 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ignore changelog, tools

#790 Zeus - Fix unable to hear players on ships
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_core/fnc_updateSelf.sqf
Labels: bug fix

#794 Fix units not updating in intercom
  addons/sys_intercom/fnc_saveStationConfiguration.sqf
Labels: bug fix

#795 Fix Intercom and rack persistence for JIP players
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_configIntercom.sqf
  addons/sys_intercom/fnc_initVehicleIntercom.sqf
  addons/sys_intercom/vic3/fnc_vic3ffcsConfig.sqf
Labels: bug fix

#797 Add simple Todo issue template
  .github/ISSUE_TEMPLATE/todo.md
Labels: ignore changelog, tools

#801 Fucking SQF order. Brackets are the solution.
  addons/sys_core/fnc_remoteStartSpeaking.sqf
Labels: bug fix

#800 Remove duplicate PTT 3 stringtable
  addons/sys_core/stringtable.xml
Labels: bug fix

#805 Zeus - Fix Voice Activation
  extensions/src/ACRE2TS/TS3Client.cpp
Labels: bug fix

#807 Prettify Intercom UI keybind documentation 2
  docs/wiki/user/vehicle-racks.md
Labels: documentation, ignore changelog

#811 Correct GSA deploy function header
  addons/sys_gsa/fnc_deploy.sqf
Labels: cleanup

#810 German Translation Finished (sort of)
  addons/ace_interact/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_signal/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#815 Fix uniqueItems script error in scheduled
  addons/sys_core/fnc_uniqueItems.sqf
Labels: bug fix, optimization

#813 Add note about 3rd party mods to Bug Report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ignore changelog, tools
