Repository IDI-Systems/acre2, pull requests merged in 2019-05, with the labels that each got.

#639 Antenna groundspike
  addons/ace_interact/fnc_radioListChildrenActions.sqf
  addons/sys_antenna/CfgAcreComponents.hpp
  addons/sys_antenna/binary/groundspike_2430cm_gain.aba
  addons/sys_antenna/binary/groundspike_2430cm_mast_gain.aba
  addons/sys_components/fnc_findAntenna.sqf
  addons/sys_components/fnc_getAntennaUpVector.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/fnc_hasItem.sqf
  addons/sys_core/fnc_uniqueItems.sqf
  addons/sys_gsa/$PBOPREFIX$
  addons/sys_gsa/CfgEventHandlers.hpp
  addons/sys_gsa/CfgVehicles.hpp
  addons/sys_gsa/CfgWeapons.hpp
  addons/sys_gsa/XEH_PREP.hpp
  addons/sys_gsa/XEH_postInit.sqf
  addons/sys_gsa/XEH_preInit.sqf
  addons/sys_gsa/XEH_preStart.sqf
  addons/sys_gsa/config.cpp
  addons/sys_gsa/data/models/acre_antennabag.p3d
  addons/sys_gsa/data/models/acre_antennabag.rvmat
  addons/sys_gsa/data/models/acre_antennabag_co.paa
  addons/sys_gsa/data/models/acre_antennabag_nohq.paa
  addons/sys_gsa/data/ui/acre_antennabag_icon.paa
  addons/sys_gsa/data/vhf30108/models/cabel.rvmat
  addons/sys_gsa/data/vhf30108/models/cabel_as.paa
  addons/sys_gsa/data/vhf30108/models/cabel_co.paa
  addons/sys_gsa/data/vhf30108/models/cabel_nohq.paa
  addons/sys_gsa/data/vhf30108/models/cabel_smdi.paa
  addons/sys_gsa/data/vhf30108/models/vhf30108.p3d
  addons/sys_gsa/data/vhf30108/models/vhf30108.rvmat
  addons/sys_gsa/data/vhf30108/models/vhf30108_as.paa
  addons/sys_gsa/data/vhf30108/models/vhf30108_co.paa
  addons/sys_gsa/data/vhf30108/models/vhf30108_nohq.paa
  addons/sys_gsa/data/vhf30108/models/vhf30108_smdi.paa
  addons/sys_gsa/data/vhf30108/models/vhf30108_spike.rvmat
  addons/sys_gsa/data/vhf30108/models/vhf30108spike.p3d
  addons/sys_gsa/data/vhf30108/ui/icon_antenna_ca.paa
  addons/sys_gsa/data/vhf30108/ui/spike.jpg
  addons/sys_gsa/data/vhf30108/ui/spikeMast.jpg
  addons/sys_gsa/fnc_connect.sqf
  addons/sys_gsa/fnc_connectChildrenActions.sqf
  addons/sys_gsa/fnc_deploy.sqf
  addons/sys_gsa/fnc_disconnect.sqf
  addons/sys_gsa/fnc_externalAntennaPFH.sqf
  addons/sys_gsa/fnc_getConnectedGsa.sqf
  addons/sys_gsa/fnc_handleMast.sqf
  addons/sys_gsa/fnc_initGsa.sqf
  addons/sys_gsa/fnc_initRadio.sqf
  addons/sys_gsa/fnc_isAntennaConnected.sqf
  addons/sys_gsa/fnc_isRadioCompatible.sqf
  addons/sys_gsa/fnc_pickUp.sqf
  addons/sys_gsa/script_component.hpp
  addons/sys_gsa/stringtable.xml
  addons/sys_prc152/prc152_RadioDialog.hpp
  addons/sys_radio/fnc_initDefaultRadio.sqf
  extras/antennas/groundspike_2430cm.inp
  extras/antennas/groundspike_2430cm.nec
  extras/antennas/groundspike_2430cm_mast.inp
  extras/antennas/groundspike_2430cm_mast.nec
Labels: enhancement, needs testing

#663 Documentation for FFCS
  docs/images/intercom/anvic3_ffcs_interface.png
  docs/wiki/user/vehicle-intercom.md
Labels: documentation

#648 Added longley-rice model
  addons/sys_core/XEH_postInit.sqf
  addons/sys_signal/CfgAcreSignal.hpp
  addons/sys_signal/XEH_PREP.hpp
  addons/sys_signal/config.cpp
  addons/sys_signal/fnc_getRadioClimateCode.sqf
  addons/sys_signal/fnc_getSignal.sqf
  addons/sys_signal/initSettings.sqf
  addons/sys_signal/script_component.hpp
  docs/wiki/frameworks/custom-signal-processing.md
  docs/wiki/user/radio-signal-loss.md
  extensions/src/ACRE2Arma/signal/antenna/antenna.cpp
  extensions/src/ACRE2Arma/signal/antenna/antenna.hpp
  extensions/src/ACRE2Arma/signal/antenna/antenna_library.cpp
  extensions/src/ACRE2Arma/signal/antenna/antenna_library.hpp
  extensions/src/ACRE2Arma/signal/map/map.cpp
  extensions/src/ACRE2Arma/signal/map/map.hpp
  extensions/src/ACRE2Arma/signal/models/arcade.cpp
  extensions/src/ACRE2Arma/signal/models/arcade.hpp
  extensions/src/ACRE2Arma/signal/models/longleyRice.cpp
  extensions/src/ACRE2Arma/signal/models/longleyRice.hpp
  extensions/src/ACRE2Arma/signal/models/longleyRice_itm.cpp
  extensions/src/ACRE2Arma/signal/models/longleyRice_itwom3.0.cpp
  extensions/src/ACRE2Arma/signal/models/los_simple.cpp
  extensions/src/ACRE2Arma/signal/models/models_common.hpp
  extensions/src/ACRE2Arma/signal/signal.hpp
Labels: enhancement, super anal

#666 Build optionals into launchable mod folders
  tools/make.py
Labels: enhancement, ignore changelog, tools

#667 Fix GSA Spanish stringtable
  addons/sys_gsa/stringtable.xml
Labels: bug fix, ignore changelog

#590 Zeus Improvements
  addons/main/script_mod.hpp
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_inRange.sqf
  addons/sys_core/fnc_inZeus.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_core/fnc_updateSelf.sqf
  addons/sys_core/script_component.hpp
  addons/sys_gui/fnc_onInventoryRadioDoubleClick.sqf
  addons/sys_zeus/$PBOPREFIX$
  addons/sys_zeus/CfgEventHandlers.hpp
  addons/sys_zeus/CfgVehicles.hpp
  addons/sys_zeus/XEH_PREP.hpp
  addons/sys_zeus/XEH_postInit.sqf
  addons/sys_zeus/XEH_preInit.sqf
  addons/sys_zeus/XEH_preStart.sqf
  addons/sys_zeus/config.cpp
  addons/sys_zeus/fnc_handleZeusInterfaceToggle.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPress.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPressUp.sqf
  addons/sys_zeus/fnc_setUsePlayer.sqf
  addons/sys_zeus/initSettings.sqf
  addons/sys_zeus/script_component.hpp
  addons/sys_zeus/stringtable.xml
Labels: enhancement, feature request

#671 Improve README.md
  README.md
Labels: ignore changelog, super anal

#677 Add Steam Workshop GM Compatibility and Dev Build release destinations
  extras/logos/acre2_gm_compat_large-logo.png
  extras/logos/acre2_gm_compat_large-logo.psd
  extras/logos/acre2_gm_compat_small-logo.png
  manifest.json
Labels: CI, tools

#679 Remove debug log
  extensions/src/ACRE2Arma/signal/models/longleyRice.cpp
Labels: ignore changelog, trivial

#681 Pass on PRC343
  addons/sys_prc343/functions/fnc_onVolumeKnobPress.sqf
  addons/sys_prc343/functions/fnc_zoomChannelBlockSelector.sqf
  addons/sys_prc343/radio/fnc_getChannelDescription.sqf
  addons/sys_prc343/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc343/radio/fnc_getState.sqf
  addons/sys_prc343/radio/fnc_handleEndTransmission.sqf
  addons/sys_prc343/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_prc343/radio/fnc_handlePTTDown.sqf
  addons/sys_prc343/radio/fnc_handlePTTUp.sqf
Labels: cleanup, enhancement

#682 Pass PRC148
  addons/sys_prc148/menus/fnc_PFH.sqf
  addons/sys_prc148/menus/fnc_changeState.sqf
  addons/sys_prc148/menus/fnc_delayFunction.sqf
  addons/sys_prc148/menus/fnc_displayLine.sqf
  addons/sys_prc148/menus/fnc_frequencyToString.sqf
  addons/sys_prc148/menus/fnc_handleEscButton.sqf
  addons/sys_prc148/menus/fnc_handleMenuButtonEnter.sqf
  addons/sys_prc148/menus/fnc_handleMenuDirButton.sqf
  addons/sys_prc148/menus/fnc_menuMoveCursor.sqf
  addons/sys_prc148/menus/fnc_onButtonPress.sqf
  addons/sys_prc148/menus/fnc_onChannelKnobPress.sqf
  addons/sys_prc148/menus/fnc_onVolumeKnobPress.sqf
  addons/sys_prc148/menus/fnc_removeAnimation.sqf
  addons/sys_prc148/menus/fnc_setCursor.sqf
  addons/sys_prc148/menus/fnc_setText.sqf
  addons/sys_prc148/menus/fnc_showMenu.sqf
  addons/sys_prc148/menus/fnc_startFlashText.sqf
  addons/sys_prc148/menus/fnc_toggleButtonPressDown.sqf
  addons/sys_prc148/menus/fnc_updateChannelData.sqf
  addons/sys_prc148/radio/fnc_getChannelData.sqf
  addons/sys_prc148/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc148/radio/fnc_getOnOffState.sqf
  addons/sys_prc148/radio/fnc_getState.sqf
  addons/sys_prc148/radio/fnc_getVolume.sqf
  addons/sys_prc148/radio/fnc_handleBeginTransmission.sqf
  addons/sys_prc148/radio/fnc_handleEndTransmission.sqf
  addons/sys_prc148/radio/fnc_handleMultipleTransmissions.sqf
  addons/sys_prc148/radio/fnc_handlePTTDown.sqf
  addons/sys_prc148/radio/fnc_handlePTTUp.sqf
  addons/sys_prc148/radio/fnc_isExternalAudio.sqf
  addons/sys_prc148/radio/fnc_setCurrentChannel.sqf
  addons/sys_prc148/radio/fnc_setOnOffState.sqf
  addons/sys_prc148/radio/fnc_setSpatial.sqf
  addons/sys_prc148/radio/fnc_setState.sqf
  addons/sys_prc148/radio/fnc_setVolume.sqf
  addons/sys_prc148/states/AccessDenied.sqf
  addons/sys_prc148/states/ChannelDisplays.sqf
  addons/sys_prc148/states/Group.sqf
  addons/sys_prc148/states/MainDisplays.sqf
  addons/sys_prc148/states/ModeDisplays.sqf
  addons/sys_prc148/states/OffDisplay.sqf
  addons/sys_prc148/states/ProgramDisplays.sqf
  addons/sys_prc148/states/ProgrammingDisplays.sqf
Labels: cleanup, enhancement
