Repository IDI-Systems/acre2, pull requests merged in 2019-02, with the labels that each got.

#625 Sys core cleanup and fixes to setRevealAI
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/fnc_aliveMonitor.sqf
  addons/sys_core/fnc_callExt.sqf
  addons/sys_core/fnc_cycleLanguage.sqf
  addons/sys_core/fnc_disableRevealAI.sqf
  addons/sys_core/fnc_enableRevealAI.sqf
  addons/sys_core/fnc_findOcclusion.sqf
  addons/sys_core/fnc_getAlive.sqf
  addons/sys_core/fnc_getCompartment.sqf
  addons/sys_core/fnc_handleGetPluginVersion.sqf
  addons/sys_core/fnc_monitorAiPFH.sqf
  addons/sys_core/fnc_muting.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_processVehicleSystemAccessArray.sqf
  addons/sys_core/fnc_setRevealToAI.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_core/fnc_switchRadioEar.sqf
  addons/sys_core/fnc_updateSelf.sqf
  addons/sys_core/initSettings.sqf
  addons/sys_core/script_component.hpp
Labels: bug fix, enhancement

#628 Disable performance counters
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_getSpeakingLanguageId.sqf
  addons/sys_core/fnc_processRadioSpeaker.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_data/fnc_clientHandleJipData.sqf
  addons/sys_prc152/menus/fnc_clearDisplay.sqf
  addons/sys_prc152/menus/fnc_onButtonPress.sqf
  addons/sys_prc152/menus/fnc_renderText.sqf
  addons/sys_prc152/menus/fnc_setRowText.sqf
  addons/sys_prc152/menus/types/Display.sqf
  addons/sys_prc152/menus/types/Static.sqf
Labels: enhancement

#631 Fix intercom volume (CBA Hash conversion)
  addons/sys_intercom/fnc_getVolumeIntercomUnit.sqf
Labels: bug fix

#632 Add radio volume getter and setter to functions
  addons/api/CfgFunctions.hpp
Labels: enhancement

#636 Display radio number in front of radio in ACE self-interact
  addons/ace_interact/fnc_radioListChildrenActions.sqf
Labels: enhancement

#637 Fix links in GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tools
