Repository IDI-Systems/acre2, pull requests merged in 2019-10, with the labels that each got.

#846 Non-Blocking Zeus Speak Keybind
  addons/sys_zeus/fnc_handleZeusSpeakPress.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPressUp.sqf
Labels: bug fix

#834 Zeus - Fix Angles and Occlusion
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_updateSelf.sqf
Labels: bug fix

#849 Minor intercom cleanup
  addons/sys_intercom/fnc_closeGui.sqf
  addons/sys_intercom/fnc_getStationConfiguration.sqf
  addons/sys_intercom/fnc_handlePttKeyPress.sqf
  addons/sys_intercom/fnc_handlePttKeyPressUp.sqf
  addons/sys_intercom/fnc_setStationConfiguration.sqf
  addons/sys_intercom/fnc_setStationUnit.sqf
Labels: cleanup

#850 Revert use of == and use isEqualTo
  addons/sys_intercom/fnc_setStationConfiguration.sqf
Labels: bug fix

#851 The love of working cross-projects...
  addons/sys_intercom/fnc_setStationConfiguration.sqf
Labels: bug fix, ignore changelog

#856 Update Japanese translation
  addons/sys_core/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation
