Repository IDI-Systems/acre2, pull requests merged in 2020-06, with the labels that each got.

#973 Extension - Multi-thread init pbo/file scan
  extensions/src/ACRE2Arma/common/pbo/search.cpp
Labels: optimization

#975 Extension - Limit number of pbo scan threads
  extensions/src/ACRE2Arma/common/pbo/search.cpp
  extensions/src/ACRE2Arma/common/pbo/search.hpp
Labels: bug fix, ignore changelog

#977 Add missing includes from spectator-radios
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
Labels: ignore changelog, tools

#953 Extensions - Fix pipe permission issues
  extensions/src/ACRE2Core/NamedPipeServer.cpp
Labels: bug fix, needs testing

#968 Core - Add outgoing spectator transmissions
  addons/sys_core/fnc_speaking.sqf
  addons/sys_modes/fnc_sc_speaking.sqf
  addons/sys_modes/fnc_sem70akw_speaking.sqf
Labels: enhancement, needs testing

#982 Data - Fix data sync log
  addons/sys_data/fnc_serverHandleJip.sqf
Labels: bug fix
