Repository IDI-Systems/acre2, pull requests merged in 2020-01, with the labels that each got.

#879 Fix stringtable
  addons/sys_core/stringtable.xml
Labels: ignore changelog

#880 Intercom - fix exitWith if invalid unit
  addons/sys_intercom/fnc_getStationConfiguration.sqf
  addons/sys_intercom/fnc_saveStationConfiguration.sqf
  addons/sys_intercom/fnc_setStationConfiguration.sqf
  addons/sys_intercom/fnc_setStationUnit.sqf
Labels: bug fix, ignore changelog

#881 Fix version (patch) comparison and log
  addons/sys_core/fnc_handleGetPluginVersion.sqf
  addons/sys_server/XEH_postInitServer.sqf
Labels: bug fix
