Repository IDI-Systems/acre2, pull requests merged in 2020-07, with the labels that each got.

#979 Extension - Fix map loading on 32-bit
  extensions/src/ACRE2Arma/common/wrp/landscape.cpp
Labels: bug fix

#987 Tools - Fix make.py rebuild on last extension
  tools/make.py
Labels: bug fix, ignore changelog, tools

#990 Add speaking UI to spectator displays
  addons/sys_radio/XEH_PREP.hpp
  addons/sys_radio/fnc_getRadioIdNumber.sqf
  addons/sys_spectator/XEH_PREP.hpp
  addons/sys_spectator/fnc_handleKeyDown.sqf
  addons/sys_spectator/fnc_handleStartedSpeaking.sqf
  addons/sys_spectator/fnc_handleStoppedSpeaking.sqf
  addons/sys_spectator/fnc_handleUpdate.sqf
  addons/sys_spectator/fnc_initDisplay.sqf
  addons/sys_spectator/fnc_refreshSpeakingList.sqf
  addons/sys_spectator/fnc_spectatorACEDisplayLoad.sqf
  addons/sys_spectator/fnc_spectatorEGDisplayLoad.sqf
  addons/sys_spectator/gui.hpp
  addons/sys_spectator/script_component.hpp
Labels: feature request

#989 Fix use of ATLtoASL on modelToWorld positions
  addons/sys_components/fnc_findAntenna.sqf
  addons/sys_prc148/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc152/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_sem52sl/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_sem70/radio/fnc_getExternalAudioPosition.sqf
Labels: bug fix

#991 Documentation - Add API functions
  .github/workflows/arma.yml
  addons/api/fnc_babelSetSpokenLanguages.sqf
  addons/api/fnc_babelSetupMission.sqf
  addons/api/fnc_getAllRadioOfType.sqf
  addons/api/fnc_getDefaultChannels.sqf
  addons/api/fnc_hasKindOfRadio.sqf
  addons/api/fnc_isSpectator.sqf
  addons/api/fnc_setCustomSignalFunc.sqf
  addons/api/fnc_setDefaultChannels.sqf
  docs/_includes/custom/functions-list-api.html
  docs/_includes/custom/functions-list.html
  docs/tools/document_functions.py
  docs/wiki/frameworks/functions-list.md
Labels: documentation, tools

#993 API - Rename getAllRadioOfType to getAllRadiosByType
  addons/api/CfgFunctions.hpp
  addons/api/fnc_getAllRadiosByType.sqf
  docs/_includes/custom/functions-list-api.html
Labels: enhancement

#984 Improve signal calc when antennas are at the same position
  extensions/src/ACRE2Arma/common/arguments.hpp
  extensions/src/ACRE2Arma/signal/antenna/antenna.cpp
  extensions/src/ACRE2Arma/signal/models/arcade.cpp
  extensions/src/ACRE2Arma/signal/models/los_simple.cpp
  extensions/src/ACRE2Arma/signal/signal.hpp
Labels: bug fix

#992 Add Spectator Displays documentation
  docs/_data/sidebar.yml
  docs/wiki/frameworks/spectator-displays.md
Labels: documentation
