Repository IDI-Systems/acre2, pull requests merged in 2020-09, with the labels that each got.

#1018 God Mode - Add ping sounds and Fix VAD compatibility
  addons/sys_godmode/XEH_postInit.sqf
  addons/sys_godmode/fnc_handlePttKeyPress.sqf
  addons/sys_godmode/fnc_handlePttKeyPressUp.sqf
  addons/sys_godmode/script_component.hpp
  addons/sys_sounds/CfgAcreSounds.hpp
  addons/sys_sounds/sounds/god_beep.b64
  addons/sys_sounds/sounds/god_ping_off.b64
  addons/sys_sounds/sounds/god_ping_on.b64
  extensions/src/ACRE2TS/TS3Client.cpp
  extensions/src/ACRE2TS/TS3Client.h
  extensions/src/ACRE2TS/TsCallbacks_speaking.cpp
  extras/sounds/god_beep.wav
  extras/sounds/god_ping_off.wav
  extras/sounds/god_ping_on.wav
  extras/sounds/god_source.wav
Labels: bug fix, enhancement

#1020 Translations - Add / Update French
  addons/sys_core/stringtable.xml
  addons/sys_godmode/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_spectator/stringtable.xml
Labels: translation

#1019 List - Improve Notification System and God Mode
  addons/ace_interact/XEH_postInitClient.sqf
  addons/ace_interact/script_component.hpp
  addons/api/CfgFunctions.hpp
  addons/api/fnc_addNotificationDisplay.sqf
  addons/sys_core/CfgEventHandlers.hpp
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_arsenalClose.sqf
  addons/sys_core/fnc_arsenalOpen.sqf
  addons/sys_core/fnc_avTerminalDisplayLoad.sqf
  addons/sys_core/fnc_cycleLanguage.sqf
  addons/sys_core/fnc_handleMultiPttKeyPressUp.sqf
  addons/sys_core/fnc_showBroadCastHint.sqf
  addons/sys_core/fnc_switchChannelFast.sqf
  addons/sys_core/fnc_toggleHeadset.sqf
  addons/sys_godmode/XEH_postInit.sqf
  addons/sys_godmode/XEH_preInit.sqf
  addons/sys_godmode/fnc_addDisplayPassthroughKeys.sqf
  addons/sys_godmode/fnc_handlePttKeyPress.sqf
  addons/sys_godmode/fnc_handlePttKeyPressUp.sqf
  addons/sys_list/XEH_PREP.hpp
  addons/sys_list/XEH_postInit.sqf
  addons/sys_list/XEH_preInit.sqf
  addons/sys_list/fnc_addDisplaySupport.sqf
  addons/sys_list/fnc_cycleRadios.sqf
  addons/sys_list/fnc_displayHint.sqf
  addons/sys_list/fnc_getActiveDisplay.sqf
  addons/sys_list/fnc_hideHint.sqf
  addons/sys_list/fnc_showHintBox.sqf
  addons/sys_list/list_dialog.hpp
  addons/sys_list/script_component.hpp
  addons/sys_list/script_dialog_defines.hpp
  include/a3/ui_f/hpp/defineResinclDesign.inc
  include/a3/ui_f_curator/ui/defineResinclDesign.inc
Labels: enhancement

#1022 GUI - Fix Antenna Elevation indicator 3rd party compatibility
  addons/sys_gui/RscInGameUI.hpp
  addons/sys_gui/config.cpp
  addons/sys_gui/fnc_antennaElevationDisplay.sqf
Labels: bug fix

#1025 API - Fix type check in `setPTTDelay`
  addons/api/fnc_setPTTDelay.sqf
Labels: bug fix
