Repository IDI-Systems/acre2, pull requests merged in 2020-04, with the labels that each got.

#894 Server - Fix radio replace warning concatenation
  addons/sys_server/fnc_masterIdTracker.sqf
Labels: bug fix

#896 Tools - Fix HEMTT version set
  hemtt.toml
Labels: ignore changelog, tools

#902 Core - Fix version display on extension installation
  addons/sys_core/steam_boot.sqf
Labels: bug fix

#848 API - Add unit loadout filtering
  addons/api/CfgFunctions.hpp
  addons/api/fnc_filterUnitLoadout.sqf
Labels: feature request

#898 Compatibility - Add loadout filter to ACE3 Respawn Save Gear
  addons/ace_interact/XEH_postInitClient.sqf
Labels: compatibility

#906 Components - Fix receiving rack antenna search
  addons/sys_components/fnc_findAntenna.sqf
Labels: bug fix

#905 Intercom - Allow usage underwater
  addons/sys_core/fnc_processDirectSpeaker.sqf
Labels: enhancement

#897 GUI - Hide antenna display in cargo seat or no radio
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_components/fnc_getAntennaUpVector.sqf
  addons/sys_components/fnc_toggleAntennaDir.sqf
  addons/sys_core/fnc_setFullDuplex.sqf
  addons/sys_core/fnc_setInterference.sqf
  addons/sys_core/fnc_setLossModelScale.sqf
  addons/sys_core/fnc_setRevealToAI.sqf
  addons/sys_gui/fnc_antennaElevationDisplay.sqf
  addons/sys_list/fnc_hideHint.sqf
Labels: bug fix

#907 ACE Interact - Only do a single call to getPlayerRadioList
  addons/ace_interact/CfgVehicles.hpp
  addons/ace_interact/fnc_radioListChildrenActions.sqf
Labels: optimization, trivial

#895 Plugin - Update TeamSpeak 3 SDK to v24
  extensions/src/ACRE2Shared/helpers.cpp
  extensions/src/ACRE2TS/TsFunctions.h
  extensions/src/ACRE2TS/inc/plugin_definitions.h
  extensions/src/ACRE2TS/inc/teamspeak/clientlib_publicdefinitions.h
  extensions/src/ACRE2TS/inc/teamspeak/public_definitions.h
  extensions/src/ACRE2TS/inc/teamspeak/public_errors_rare.h
  extensions/src/ACRE2TS/inc/teamspeak/public_rare_definitions.h
  extensions/src/ACRE2TS/inc/ts3_functions.h
Labels: TeamSpeak's fault, compatibility

#903 GUI - Fix Inventory CBA compatibility and Vehicle Info seat changing
  addons/ace_interact/config.cpp
  addons/ace_interact/fnc_radioChildrenActions.sqf
  addons/ace_interact/stringtable.xml
  addons/main/script_mod.hpp
  addons/sys_gui/CfgEventHandlers.hpp
  addons/sys_gui/XEH_PREP.hpp
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_gui/config.cpp
  addons/sys_gui/fnc_closeInventory.sqf
  addons/sys_gui/fnc_handleContextMenu.sqf
  addons/sys_gui/fnc_handleInventoryOpened.sqf
  addons/sys_gui/fnc_handleTake.sqf
  addons/sys_gui/fnc_inventoryListMouseDown.sqf
  addons/sys_gui/fnc_inventoryListMouseUp.sqf
  addons/sys_gui/fnc_inventoryMonitorPFH.sqf
  addons/sys_gui/fnc_onInventoryAction.sqf
  addons/sys_gui/fnc_onInventoryRadioDoubleClick.sqf
  addons/sys_gui/fnc_onInventoryRadioSelected.sqf
  addons/sys_gui/fnc_openInventory.sqf
  addons/sys_gui/fnc_openRadio.sqf
  addons/sys_gui/fnc_showVehicleInfo.sqf
  addons/sys_gui/fnc_uniqueArray.sqf
  addons/sys_gui/fnc_updateVehicleInfo.sqf
  addons/sys_gui/script_component.hpp
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/config.cpp
  addons/sys_intercom/fnc_enterVehicle.sqf
  addons/sys_intercom/fnc_intercomPFH.sqf
  addons/sys_intercom/fnc_seatSwitched.sqf
  addons/sys_intercom/fnc_updateVehicleInfoText.sqf
  addons/sys_rack/XEH_postInit.sqf
  addons/sys_rack/fnc_enterVehicle.sqf
  addons/sys_rack/fnc_rackPFH.sqf
  addons/sys_radio/fnc_isUniqueRadio.sqf
Labels: bug fix, cleanup

#883 Extension - Fix a memory leak and error case in PIPE_COMMAND_READ
  extensions/src/ACRE2Arma/arma2ts/CallExt_DllMain.cpp
Labels: bug fix

#887 Core - Fix updateSelf position format (Zeus over water)
  addons/sys_core/fnc_updateSelf.sqf
Labels: bug fix

#909 Core - Add debug information for reserved variable error
  addons/sys_core/fnc_processRadioSpeaker.sqf
Labels: debug

#914 Tools - Fix macro concatenation for pboProject 2.63
  addons/sys_prc117f/DialogDefines.hpp
  addons/sys_prc148/prc148_RadioDialog.hpp
  addons/sys_prc152/DialogDefines.hpp
Labels: bug fix, ignore changelog, tools

#919 Tools - Update make.py
  tools/make.py
Labels: bug fix, ignore changelog, tools

#915 117F - Fix auto-start on interface open when turned off
  addons/sys_prc117f/fnc_openGui.sqf
Labels: bug fix

#923 General - Cleanup
  addons/api/fnc_setCustomSignalFunc.sqf
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_intercom/fnc_noApiFunction.sqf
  addons/sys_sem52sl/CfgAcreRadios.hpp
  addons/sys_signal/XEH_preInit.sqf
  addons/sys_signal/initSettings.sqf
  addons/sys_signal/script_component.hpp
Labels: cleanup, needs testing

#920 Zeus - Fix hearing local sources in addition to camera sources
  addons/sys_core/fnc_processDirectSpeaker.sqf
Labels: bug fix

#885 Extensions - Fix variable shadowing
  extensions/src/ACRE2Arma/signal/models/los_simple.cpp
  extensions/src/ACRE2Arma/signal/models/los_simple.hpp
Labels: bug fix, enhancement

#857 Signal Map - Fix marker creating with `_`
  addons/sys_signalmap/fnc_setRxAreaEnd.sqf
Labels: bug fix

#924 Extensions - Fix buffer overflow in Debug builds
  extensions/src/ACRE2Arma/acre/acre.cpp
  extensions/src/ACRE2Arma/arma2ts/CallExt_DllMain.cpp
  extensions/src/ACRE2Arma/dynload/acre_dynload.cpp
  extensions/src/ACRE2Steam/CallExt_DllMain.cpp
Labels: bug fix

#918 Zeus - Fix unit muted after leaving Zeus with Spectator enabled
  addons/sys_core/fnc_spectatorOff.sqf
  addons/sys_core/fnc_spectatorOn.sqf
  addons/sys_zeus/CfgEventHandlers.hpp
  addons/sys_zeus/XEH_PREP.hpp
  addons/sys_zeus/XEH_preInit.sqf
  addons/sys_zeus/fnc_handleZeusInterfaceLoad.sqf
  addons/sys_zeus/fnc_handleZeusInterfaceToggle.sqf
  addons/sys_zeus/fnc_handleZeusInterfaceUnload.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPress.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPressUp.sqf
  addons/sys_zeus/fnc_showMessage.sqf
  addons/sys_zeus/script_component.hpp
  addons/sys_zeus/stringtable.xml
Labels: bug fix

#910 Racks - Improve intercom-only radio configuration in ACE Interact
  addons/ace_interact/fnc_radioChildrenActions.sqf
  addons/sys_gui/XEH_preInit.sqf
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_intercomPFH.sqf
  addons/sys_rack/fnc_initActionVehicle.sqf
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/fnc_rackListChildrenActions.sqf
  addons/sys_radio/fnc_canUnitTransmit.sqf
Labels: bug fix, cleanup, enhancement

#928 Documentation - Update Signal Map status
  docs/wiki/frameworks/radio-signal-debugging.md
Labels: documentation, ignore changelog

#927 Documentation - Add HEMTT instructions
  docs/wiki/development/building.md
Labels: documentation, ignore changelog

#926 Documentation - Remove checkexternal references
  docs/wiki/development/building.md
Labels: documentation

#931 Documentation - Use GitHub releases page as repository link
  README.md
Labels: documentation, ignore changelog

#930 Documentation - Add Tips and Tricks
  docs/_data/sidebar.yml
  docs/wiki/development/tips-and-tricks.md
Labels: documentation, ignore changelog

#932 Translation - Add and Improve Portuguese
  addons/ace_interact/stringtable.xml
  addons/api/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_signal/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#941 Documentation - Fix link paths in HEMTT instructions
  docs/wiki/development/building.md
Labels: documentation, ignore changelog

#934 Components - Improve getAntennaDirMan function
  addons/sys_components/XEH_PREP.hpp
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_components/fnc_getAntennaUpVector.sqf
Labels: enhancement, optimization

#945 Documentation - It is acre not intercept
  docs/wiki/development/coding-guidelines-cpp.md
Labels: documentation, ignore changelog
