Repository IDI-Systems/acre2, pull requests merged in 2020-11, with the labels that each got.

#1033 API - Optimize `setPTTDelay`
  addons/api/fnc_setPTTDelay.sqf
Labels: optimization

#1034 API - Fix scheduler issue in `getRadioByType`
  addons/api/fnc_getRadioByType.sqf
Labels: bug fix

#1036 Wiki - Add GSM and Classnames
  README.md
  docs/_data/sidebar.yml
  docs/_includes/custom/class-names.html
  docs/wiki/class-names.md
  docs/wiki/user/feature-list.md
  docs/wiki/user/ground-spike-antenna.md
Labels: documentation

#1035 Racks - Add an additional rack to helicopters
  addons/sys_rack/CfgVehicles.hpp
  addons/sys_rack/stringtable.xml
Labels: enhancement
