Repository IDI-Systems/acre2, pull requests merged in 2020-03, with the labels that each got.

#886 Update fnc_remoteStartSpeaking.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
Labels: ignore changelog

#878 Update make.py for changes to pboProject
  tools/make.py
Labels: ignore changelog, tools

#863 Update Chinese translations
  addons/main/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_rack/stringtable.xml
Labels: WIP, translation

#888 Tools - Add Release Drafter
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ignore changelog, tools

#891 Documentation - Remove Dev-Build note
  docs/wiki/frameworks/custom-signal-processing.md
Labels: documentation

#889 Adapt to HEMTT
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
  .gitignore
  .travis.yml
  addons/sys_prc117f/DialogDefines.hpp
  addons/sys_prc117f/config.cpp
  addons/sys_prc148/Data/Models/prc148.p3d
  addons/sys_prc148/Data/Models/prc148_diag.p3d
  addons/sys_prc148/prc148_RadioDialog.hpp
  addons/sys_prc152/DialogDefines.hpp
  addons/sys_prc152/config.cpp
  addons/sys_prc343/Data/models/acre_prc343_model.p3d
  addons/sys_radio/script_component.hpp
  addons/sys_sem70/CfgEventHandlers.hpp
  addons/sys_server/config.cpp
  build.bat
  build_release.bat
  extensions/src/ACRE2Arma/common/dispatch.hpp
  hemtt.toml
  include/a3/ui_f/hpp/defineCommonColors.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/x/cba/addons/main/script_macros_common.hpp
  tools/check_strings.py
  tools/setup.bat
Labels: tools

#892 Core - Initialize extension only on clients
  addons/sys_core/XEH_preStart.sqf
Labels: optimization
