Repository IDI-Systems/acre2, pull requests merged in 2020-08, with the labels that each got.

#997 Documentation - Update Debugging with Signal Map Tool
  docs/wiki/frameworks/radio-signal-debugging.md
Labels: documentation

#999 Add God Mode
  addons/api/CfgFunctions.hpp
  addons/api/fnc_godModeConfigureAccess.sqf
  addons/api/fnc_godModeModifyGroup.sqf
  addons/api/fnc_godModeSendText.sqf
  addons/api/script_component.hpp
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_handleGetClientID.sqf
  addons/sys_core/fnc_inRange.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_core/fnc_remoteStopSpeaking.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_core/initSettings.sqf
  addons/sys_core/stringtable.xml
  addons/sys_godmode/$PBOPREFIX$
  addons/sys_godmode/CfgEventHandlers.hpp
  addons/sys_godmode/XEH_PREP.hpp
  addons/sys_godmode/XEH_postInit.sqf
  addons/sys_godmode/XEH_preInit.sqf
  addons/sys_godmode/XEH_preStart.sqf
  addons/sys_godmode/config.cpp
  addons/sys_godmode/fnc_accessAllowed.sqf
  addons/sys_godmode/fnc_getUnitsBIChannel.sqf
  addons/sys_godmode/fnc_handlePttKeyPress.sqf
  addons/sys_godmode/fnc_handlePttKeyPressUp.sqf
  addons/sys_godmode/fnc_modifyAllowedUIDS.sqf
  addons/sys_godmode/fnc_modifyGroup.sqf
  addons/sys_godmode/fnc_sendText.sqf
  addons/sys_godmode/initSettings.sqf
  addons/sys_godmode/script_acre_component_defines.hpp
  addons/sys_godmode/script_component.hpp
  addons/sys_godmode/stringtable.xml
  docs/_data/sidebar.yml
  docs/wiki/user/feature-list.md
  docs/wiki/user/god-mode.md
  extensions/src/ACRE2Core/Engine.cpp
  extensions/src/ACRE2Core/startGodModeSpeaking.h
  extensions/src/ACRE2Core/stopGodModeSpeaking.h
  extensions/src/ACRE2Core/updateSpeakingData.h
  extensions/src/ACRE2Shared/Types.h
  extensions/src/ACRE2TS/TS3Client.cpp
Labels: feature request

#1003 Documentation - Fix C++ undefined behavior
  docs/wiki/development/coding-guidelines-cpp.md
Labels: documentation

#1002 Core - Cleanup debug
  addons/sys_core/fnc_processRadioSpeaker.sqf
Labels: cleanup

#1001 God Mode - Expand and Improve
  addons/api/CfgFunctions.hpp
  addons/api/config.cpp
  addons/api/fnc_godModeGetGroupTargets.sqf
  addons/api/fnc_godModeModifyGroup.sqf
  addons/api/fnc_godModeNameGroup.sqf
  addons/main/script_macros.hpp
  addons/sys_core/fnc_addDisplayPassthroughKeys.sqf
  addons/sys_core/fnc_localStartSpeaking.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_remoteStartSpeaking.sqf
  addons/sys_core/fnc_remoteStopSpeaking.sqf
  addons/sys_core/fnc_speaking.sqf
  addons/sys_godmode/XEH_PREP.hpp
  addons/sys_godmode/XEH_postInit.sqf
  addons/sys_godmode/XEH_preInit.sqf
  addons/sys_godmode/fnc_accessAllowed.sqf
  addons/sys_godmode/fnc_addDisplayPassthroughKeys.sqf
  addons/sys_godmode/fnc_getUnitsBIChannel.sqf
  addons/sys_godmode/fnc_handlePttKeyPress.sqf
  addons/sys_godmode/fnc_handlePttKeyPressUp.sqf
  addons/sys_godmode/fnc_modifyAllowedUIDS.sqf
  addons/sys_godmode/fnc_modifyGroup.sqf
  addons/sys_godmode/fnc_nameGroup.sqf
  addons/sys_godmode/fnc_sendText.sqf
  addons/sys_godmode/script_component.hpp
  addons/sys_spectator/fnc_handleStartedSpeaking.sqf
  docs/_data/sidebar.yml
  docs/wiki/frameworks/events-list.md
  docs/wiki/frameworks/god-mode.md
  docs/wiki/user/god-mode.md
  extensions/src/ACRE2Core/startZeusSpeaking.h
  extensions/src/ACRE2Core/stopZeusSpeaking.h
  extensions/src/ACRE2Core/updateSpeakingData.h
  extensions/src/ACRE2Shared/Types.h
  extensions/src/ACRE2TS/TS3Client.cpp
Labels: bug fix, enhancement

#1011 Tools - Fix function documentation script Windows compatibility
  docs/tools/document_functions.py
Labels: bug fix, ignore changelog, tools

#1013 God Mode - Fix API function argument check
  addons/api/fnc_godModeModifyGroup.sqf
Labels: bug fix

#1016 API - Cleanup deprecated functions
  addons/api/XEH_PREP.hpp
  addons/api/fnc_getDefaultChannels.sqf
  addons/api/fnc_setDefaultChannels.sqf
  addons/api/fnc_tests.sqf
Labels: cleanup
