Repository IDI-Systems/acre2, pull requests merged in 2020-05, with the labels that each got.

#947 sys_gsa - Fix pfeh not being removed
  addons/sys_gsa/XEH_preInit.sqf
  addons/sys_gsa/fnc_disconnectServer.sqf
  addons/sys_gsa/script_component.hpp
Labels: bug fix

#944 Use CBA_fnc_compileFunction for PREP_MODULE
  addons/main/script_macros.hpp
  addons/sys_server/CfgEventHandlers.hpp
  addons/sys_server/XEH_preStart.sqf
Labels: optimization

#929 Respawn - Fix MenuPosition with Spectator
  addons/sys_core/fnc_spectatorEGDisplayLoad.sqf
  addons/sys_core/fnc_spectatorEGDisplayUnload.sqf
Labels: enhancement

#643 Debug - Add dump performance counters function and cleanup
  addons/main/XEH_PREP.hpp
  addons/main/XEH_preInit.sqf
  addons/main/fnc_dumpCallStack.sqf
  addons/main/fnc_dumpPerformanceCounters.sqf
  addons/main/script_debug.hpp
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_aliveMonitor.sqf
  addons/sys_core/fnc_coreInitPFH.sqf
  addons/sys_core/fnc_getClientIdLoop.sqf
  addons/sys_core/fnc_handleMultiPttKeyPressUp.sqf
  addons/sys_core/fnc_muting.sqf
  addons/sys_core/fnc_remoteStopSpeaking.sqf
  addons/sys_core/fnc_setRevealToAI.sqf
  addons/sys_core/fnc_utilityFunction.sqf
  addons/sys_data/XEH_postInitClient.sqf
  addons/sys_external/XEH_postInit.sqf
  addons/sys_io/fnc_ping.sqf
  addons/sys_io/fnc_server.sqf
  addons/sys_io/fnc_startServer.sqf
  addons/sys_prc117f/menus/fnc_delayFunction.sqf
  addons/sys_prc117f/menus/fnc_timerFunction.sqf
  addons/sys_prc148/fnc_openGui.sqf
  addons/sys_prc148/menus/fnc_delayFunction.sqf
  addons/sys_prc152/menus/fnc_delayFunction.sqf
  addons/sys_prc152/menus/fnc_timerFunction.sqf
  addons/sys_prc343/functions/fnc_zoomChannelBlockSelector.sqf
  addons/sys_radio/fnc_monitorRadios.sqf
  addons/sys_server/XEH_postInitServer.sqf
  addons/sys_signalmap/fnc_doProcess.sqf
  addons/sys_signalmap/fnc_open.sqf
  addons/sys_zeus/fnc_handleZeusSpeakPressUp.sqf
Labels: cleanup, tools

#946 152/117F - Fix ZeroDivisor when adding spaces to channel names
  addons/sys_prc117f/farris_menus/PGM.sqf
  addons/sys_prc117f/fnc_initializeRadio.sqf
  addons/sys_prc117f/fnc_preset_information.sqf
  addons/sys_prc117f/menus/types/Alphanumeric.sqf
  addons/sys_prc117f/script_component.hpp
  addons/sys_prc152/farris_menus/PGM.sqf
  addons/sys_prc152/menus/types/Alphanumeric.sqf
  addons/sys_prc152/script_component.hpp
Labels: bug fix

#952 Documentation - Fix Examples in Headers
  addons/sys_external/fnc_allowExternalUse.sqf
  addons/sys_external/fnc_externalRadioPFH.sqf
  addons/sys_external/fnc_getExternalRadioOwner.sqf
  addons/sys_external/fnc_getExternalRadioUser.sqf
  addons/sys_external/fnc_getExternalUseStatus.sqf
  addons/sys_external/fnc_getSharedExternalRadios.sqf
  addons/sys_external/fnc_initRadio.sqf
  addons/sys_external/fnc_isExternalActionAvailable.sqf
  addons/sys_external/fnc_isExternalRadioAvailable.sqf
  addons/sys_external/fnc_isExternalRadioUsed.sqf
  addons/sys_external/fnc_isRadioShared.sqf
  addons/sys_external/fnc_startUsingExternalRadio.sqf
  addons/sys_external/fnc_stopUsingExternalRadio.sqf
  addons/sys_gsa/fnc_initRadio.sqf
Labels: documentation, ignore changelog

#951 Extensions - Fix freeze on start with Tobii EyeTracker
  extensions/src/ACRE2Arma/common/pbo/search.cpp
Labels: bug fix

#964 GUI - Close inventory context menu after using open radio action
  addons/sys_gui/XEH_postInit.sqf
Labels: enhancement

#949 GSA - Fix PFEH not being removed under some conditions
  addons/sys_gsa/XEH_postInit.sqf
  addons/sys_gsa/XEH_preInit.sqf
  addons/sys_gsa/fnc_connectServer.sqf
  addons/sys_gsa/fnc_disconnectServer.sqf
  addons/sys_gsa/fnc_externalAntennaPFH.sqf
  addons/sys_gsa/fnc_handleMast.sqf
Labels: bug fix

#965 GUI - Use XEH for inventory display initialization
  addons/sys_gui/CfgEventHandlers.hpp
  addons/sys_gui/XEH_PREP.hpp
  addons/sys_gui/XEH_postInit.sqf
  addons/sys_gui/fnc_handleInventoryOpened.sqf
  addons/sys_gui/fnc_initDisplayInventory.sqf
  addons/sys_gui/script_component.hpp
Labels: enhancement

#961 Extensions - Parse Startup Parameters Config File
  extensions/src/ACRE2Steam/CallExt_DllMain.cpp
Labels: enhancement

#957 Server - Fix masterIdTracker with multiple duplicates
  addons/sys_server/fnc_masterIdTracker.sqf
Labels: bug fix

#967 Extensions - Erase after remove
  extensions/src/ACRE2Steam/CallExt_DllMain.cpp
Labels: cleanup, ignore changelog

#933 Extensions - Improve callExt for getSignal and update dynload
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/XEH_preStart.sqf
  addons/sys_core/fnc_callExt.sqf
  addons/sys_signal/fnc_getSignal.sqf
  addons/sys_signal/fnc_handleSignalReturn.sqf
  extensions/src/ACRE2Arma/acre/acre.cpp
  extensions/src/ACRE2Arma/common/arguments.hpp
  extensions/src/ACRE2Arma/common/dispatch.hpp
  extensions/src/ACRE2Arma/common/shared.hpp
  extensions/src/ACRE2Arma/controller/controller.cpp
  extensions/src/ACRE2Arma/controller/controller.hpp
  extensions/src/ACRE2Arma/dynload/acre_dynload.cpp
  extensions/src/ACRE2Arma/dynload/dynloader.hpp
  extensions/src/ACRE2Arma/signal/signal.hpp
Labels: enhancement, optimization

#940 Various - Fix undefined functions
  addons/ace_interact/fnc_generateConnectorActions.sqf
  addons/sys_core/initSettings.sqf
  addons/sys_rack/XEH_postInit.sqf
  addons/sys_radio/fnc_handleRadioSpatialKeyPressed.sqf
  addons/sys_server/XEH_PREPServer.hpp
Labels: bug fix

#943 Intercom - Fix missing variable for JIP player
  addons/sys_intercom/fnc_configIntercom.sqf
  addons/sys_intercom/fnc_configIntercomStations.sqf
Labels: bug fix, needs testing
