Repository IDI-Systems/acre2, pull requests merged in 2021-04, with the labels that each got.

#1082 News - Add State of ACRE2
  docs/_posts/2021-04-07-state-of-acre2.md
Labels: documentation, ignore changelog

#1053 Add ACE Arsenal Stats
  addons/ace_interact/XEH_PREP.hpp
  addons/ace_interact/ace_arsenal_stats.hpp
  addons/ace_interact/config.cpp
  addons/ace_interact/fnc_arsenalStats_externalSpeaker.sqf
  addons/ace_interact/fnc_arsenalStats_frequencyRange.sqf
  addons/ace_interact/fnc_arsenalStats_transmitPower.sqf
  addons/ace_interact/stringtable.xml
  addons/sys_prc117f/CfgWeapons.hpp
  addons/sys_prc148/CfgWeapons.hpp
  addons/sys_prc152/CfgWeapons.hpp
  addons/sys_prc343/CfgWeapons.hpp
  addons/sys_prc77/CfgWeapons.hpp
  addons/sys_sem52sl/CfgWeapons.hpp
  addons/sys_sem70/CfgWeapons.hpp
Labels: feature request

#1074 Update linguist settings
  .gitattributes
Labels: documentation, ignore changelog

#1084 Documentation - Add ACE3 requirement note to GSA
  docs/wiki/user/ground-spike-antenna.md
Labels: documentation, ignore changelog

#1085 Documentation - Add Team page
  docs/_data/sidebar.yml
  docs/index.md
  docs/team.md
  docs/wiki/class-names.md
Labels: documentation

#1087 Signal - Split core signal getter
  addons/sys_signal/XEH_PREP.hpp
  addons/sys_signal/fnc_getSignal.sqf
  addons/sys_signal/fnc_getSignalCore.sqf
Labels: enhancement

#1089 News - Add New Community Home
  README.md
  docs/_posts/2016-11-25-new-documentation.md
  docs/_posts/2021-04-23-new-community-home.md
Labels: documentation

#1092 General - Make use of ConfigOf
  addons/sys_attenuate/fnc_getUnitAttenuate.sqf
  addons/sys_attenuate/fnc_getVehicleAttenuation.sqf
  addons/sys_components/fnc_findAntenna.sqf
  addons/sys_core/fnc_findOcclusion.sqf
  addons/sys_core/fnc_getCompartment.sqf
  addons/sys_gsa/fnc_connectServer.sqf
  addons/sys_gsa/fnc_isRadioCompatible.sqf
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_configInfantryPhone.sqf
  addons/sys_intercom/fnc_infantryPhoneAction.sqf
  addons/sys_intercom/fnc_initVehicleIntercom.sqf
  addons/sys_rack/fnc_configWiredIntercoms.sqf
  addons/sys_rack/fnc_initVehicle.sqf
  addons/sys_server/fnc_masterIdTracker.sqf
Labels: optimization
