Repository IDI-Systems/acre2, pull requests merged in 2021-03, with the labels that each got.

#1068 SEM70 - Fix frequency setting on dedicated server
  addons/sys_sem70/functions/fnc_onMHzKnobTurn.sqf
  addons/sys_sem70/functions/fnc_onkHzKnobTurn.sqf
  addons/sys_sem70/radio/fnc_setCurrentChannel.sqf
Labels: bug fix, needs testing

#1038 API - Add Audio Source Control
  addons/api/CfgFunctions.hpp
  addons/api/fnc_getRadioAudioSource.sqf
  addons/api/fnc_isRadioSpeaker.sqf
  addons/api/fnc_setRadioAudioSource.sqf
  addons/api/fnc_setRadioSpeaker.sqf
Labels: feature request

#1072 SEM70 - Fix duplicated knob picture
  addons/sys_sem70/data/knobs/mhz/mhz_5.paa
Labels: bug fix, trivial

#1073 Core - Improve listening position smoothness
  addons/sys_core/fnc_updateSelf.sqf
Labels: bug fix

#1076 Intercom - Remove intercom PFH when ejecting from aircraft
  addons/sys_intercom/fnc_enterVehicle.sqf
Labels: bug fix
