Repository IDI-Systems/acre2, pull requests merged in 2021-02, with the labels that each got.

#1059 Misc - Fix various macro usage
  addons/api/fnc_tests.sqf
  addons/sys_prc117f/menus/types/Frequency.sqf
  addons/sys_prc117f/menus/types/List.sqf
  addons/sys_prc117f/menus/types/Number.sqf
  addons/sys_prc152/menus/types/Frequency.sqf
  addons/sys_prc152/menus/types/List.sqf
  addons/sys_prc152/menus/types/Number.sqf
Labels: bug fix, ignore changelog

#1060 Configs - Convert all true/false in configs to 0/1
  addons/api/config.cpp
  addons/sys_antenna/CfgAcreComponents.hpp
  addons/sys_components/CfgAcreComponents.hpp
  addons/sys_gsa/config.cpp
  addons/sys_intercom/vic3/vic3ffcs_dialogClasses.hpp
  addons/sys_prc117f/RadioDialogClasses.hpp
  addons/sys_prc148/RadioDialogClasses.hpp
  addons/sys_prc152/RadioDialogClasses.hpp
  addons/sys_prc343/RadioDialogClasses.hpp
  addons/sys_prc77/RadioDialogClasses.hpp
  addons/sys_radio/config.cpp
  addons/sys_sem52sl/RadioDialogClasses.hpp
  addons/sys_sem70/RadioDialogClasses.hpp
  addons/sys_sounds/config.cpp
Labels: cleanup, enhancement, ignore changelog

#1058 Extensions - Update to C++20
  extensions/src/ACRE2Arma/common/p3d/compressed.hpp
  extensions/src/ACRE2Arma/common/wrp/landscape.hpp
  extensions/src/ACRE2Arma/signal/map/map.cpp
  extensions/src/ACRE2Core/ext_handleGetClientID.h
  extensions/src/ACRE2Core/ext_remoteStartSpeaking.h
  extensions/src/ACRE2Core/ext_remoteStopSpeaking.h
  extensions/src/ACRE2Core/ext_reset.h
  extensions/src/ACRE2Core/getClientID.h
  extensions/src/ACRE2Core/getPluginVersion.h
  extensions/src/ACRE2Core/loadSound.h
  extensions/src/ACRE2Core/localMute.h
  extensions/src/ACRE2Core/ping.h
  extensions/src/ACRE2Core/playSound.h
  extensions/src/ACRE2Core/setMuted.h
  extensions/src/ACRE2Core/setPTTKeys.h
  extensions/src/ACRE2Core/setSelectableVoiceCurve.h
  extensions/src/ACRE2Core/setSetting.h
  extensions/src/ACRE2Core/setSoundSystemMasterOverride.h
  extensions/src/ACRE2Core/setTs3ChannelDetails.h
  extensions/src/ACRE2Core/setVoiceCurveModel.h
  extensions/src/ACRE2Core/startGodModeSpeaking.h
  extensions/src/ACRE2Core/startIntercomSpeaking.h
  extensions/src/ACRE2Core/startRadioSpeaking.h
  extensions/src/ACRE2Core/startZeusSpeaking.h
  extensions/src/ACRE2Core/stopGodModeSpeaking.h
  extensions/src/ACRE2Core/stopIntercomSpeaking.h
  extensions/src/ACRE2Core/stopRadioSpeaking.h
  extensions/src/ACRE2Core/stopZeusSpeaking.h
  extensions/src/ACRE2Core/updateSelf.h
  extensions/src/ACRE2Core/updateSpeakingData.h
  extensions/src/ACRE2Shared/ACRE_VECTOR.h
  extensions/src/ACRE2Shared/IRpcFunction.h
  extensions/src/ACRE2Shared/Log.cpp
  extensions/src/ACRE2Shared/Log.h
  extensions/src/ACRE2Shared/Macros.h
  extensions/src/ACRE2Shared/TextMessage.cpp
  extensions/src/ACRE2Shared/TextMessage.h
  extensions/src/ACRE2Shared/ini_reader.cpp
Labels: enhancement

#1062 CI - Add release and development build workflow
  .github/workflows/release.yml
Labels: tools

#1061 GSA - Fix connection issues on dedicated server
  addons/sys_components/fnc_detachComponentHandler.sqf
  addons/sys_data/fnc_handleSetData.sqf
  addons/sys_radio/fnc_getRadioObject.sqf
Labels: bug fix, needs testing

#1049 Attenuation - Improve handling of 1st person spectating
  addons/sys_attenuate/fnc_getUnitAttenuate.sqf
  addons/sys_attenuate/fnc_getVehicleAttenuation.sqf
  addons/sys_core/fnc_findOcclusion.sqf
  addons/sys_core/fnc_speaking.sqf
Labels: bug fix

#1064 PRC148 - Fix invalid knob position after call to setRadioChannel API
  addons/sys_prc148/radio/fnc_setCurrentChannel.sqf
Labels: bug fix

#1066 GSA - Fix disconnected unit notification
  addons/sys_gsa/fnc_disconnectServer.sqf
Labels: bug fix

#1067 CI - Fix missing Wav2B64 extra
  .github/workflows/release.yml
Labels: bug fix, ignore changelog, tools

#1063 SEM70 - Prep functions at preStart
  addons/sys_sem70/CfgEventHandlers.hpp
  addons/sys_sem70/XEH_PREP.hpp
  addons/sys_sem70/XEH_preInit.sqf
  addons/sys_sem70/XEH_preStart.sqf
Labels: bug fix, needs testing

#1031 Add Gestures
  addons/sys_gestures/$PBOPREFIX$
  addons/sys_gestures/CfgEventHandlers.hpp
  addons/sys_gestures/CfgGesturesMale.hpp
  addons/sys_gestures/CfgMovesBasic.hpp
  addons/sys_gestures/XEH_PREP.hpp
  addons/sys_gestures/XEH_postInit.sqf
  addons/sys_gestures/XEH_preInit.sqf
  addons/sys_gestures/XEH_preStart.sqf
  addons/sys_gestures/config.cpp
  addons/sys_gestures/fnc_isHeadsetRadio.sqf
  addons/sys_gestures/fnc_startedSpeaking.sqf
  addons/sys_gestures/fnc_stopGesture.sqf
  addons/sys_gestures/fnc_stoppedSpeaking.sqf
  addons/sys_gestures/initSettings.sqf
  addons/sys_gestures/script_component.hpp
  addons/sys_gestures/stringtable.xml
  docs/_data/sidebar.yml
  docs/wiki/user/gestures.md
Labels: feature request, hacktoberfest-accepted

#1069 Wiki - Add dev tag and remove redundant line in Gestures
  docs/wiki/user/gestures.md
Labels: documentation, ignore changelog

#1070 Gestures - Fix Event Handlers when switching units
  addons/sys_gestures/XEH_postInit.sqf
  addons/sys_gestures/script_component.hpp
Labels: bug fix
