Repository IDI-Systems/acre2, pull requests merged in 2021-05, with the labels that each got.

#1091 API - Improve and Fix some API functions
  addons/api/fnc_getAllRadiosByType.sqf
  addons/api/fnc_getRadioByType.sqf
  addons/api/fnc_hasBaseRadio.sqf
  addons/api/fnc_hasKindOfRadio.sqf
  addons/api/fnc_hasRadio.sqf
  addons/api/fnc_initVehicleRacks.sqf
  addons/api/fnc_isRadio.sqf
  addons/api/fnc_setMultiPushToTalkAssignment.sqf
  addons/api/fnc_setRadioChannel.sqf
  addons/api/fnc_tests.sqf
Labels: bug fix, enhancement, optimization

#1102 Documentation - Reference #acre2 channel for Slack
  .github/release-drafter.yml
  README.md
  docs/_data/topnav.yml
Labels: documentation, ignore changelog

#1107 Translations - Add French Translations
  addons/ace_interact/stringtable.xml
  addons/sys_gestures/stringtable.xml
Labels: translation

#1113 API - Fix `setRadioChannel` for PRC77
  addons/api/fnc_setRadioChannel.sqf
Labels: bug fix

#1110 TeamSpeak - Move plugin log location to writeable location and fix metadata segfault
  extensions/src/ACRE2Core/Engine.cpp
  extensions/src/ACRE2Core/Engine.h
  extensions/src/ACRE2TS/TS3Client.cpp
Labels: bug fix
