Repository IDI-Systems/acre2, pull requests merged in 2021-01, with the labels that each got.

#1052 Documentation - Fix God Mode formatting
  docs/wiki/user/god-mode.md
Labels: documentation, ignore changelog, trivial

#1051 Tools - Use hemtt in build.py if installed
  tools/build.py
Labels: ignore changelog, tools

#1050 CI - Add unbinarized HEMTT builds (no extensions)
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
  .github/workflows/release-drafter.yml
  .gitignore
  hemtt.toml
  include/a3/data_f/$PBOPREFIX$
  include/a3/data_f/penetration/plastic.bisurf
  include/a3/data_f/penetration/plastic.rvmat
Labels: tools

#1010 Tools - Add Clang
  extensions/src/.clang-format
  extensions/src/.clang-tidy
Labels: ignore changelog, tools

#1057 Fix various debug macro usage
  addons/api/fnc_addRackToVehicle.sqf
  addons/api/fnc_godModeGetGroupTargets.sqf
  addons/api/fnc_godModeModifyGroup.sqf
  addons/api/fnc_godModeNameGroup.sqf
  addons/api/fnc_godModeSendText.sqf
  addons/sys_godmode/fnc_modifyGroup.sqf
  addons/sys_rack/fnc_onReturnRadioId.sqf
Labels: bug fix
