Repository IDI-Systems/acre2, pull requests merged in 2021-11, with the labels that each got.

#1159 Radio - Allow blocking all radio transmissions on a unit
  addons/sys_core/fnc_onPlayerKilled.sqf
  addons/sys_radio/fnc_canUnitTransmit.sqf
Labels: enhancement

#1162 General - Display missing compatibility warning for Global Mobilization
  addons/main/CfgSettings.hpp
Labels: enhancement, compatibility

#1153 Translations - Add missing German and Italian
  addons/ace_interact/stringtable.xml
  addons/api/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_godmode/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_signal/stringtable.xml
  addons/sys_spectator/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#1166 Tools - Add shebang to SQFC and includes update scripts
  tools/compile_sqf.py
  tools/updateIncludes.py
Labels: tools

#1168 Tools - Update includes
  include/a3/ui_f/hpp/defineResincl.inc
Labels: tools, ignore changelog

#1165 Documentation - Use SQF highlighting
  docs/wiki/development/building.md
  docs/wiki/development/coding-guidelines-cpp.md
  docs/wiki/development/coding-guidelines-sqf.md
  docs/wiki/frameworks/custom-signal-processing.md
  docs/wiki/frameworks/god-mode.md
  docs/wiki/frameworks/spectator-displays.md
Labels: documentation

#1167 Tools - Require SQFC
  docs/wiki/development/building.md
  hemtt.toml
  tools/compile_sqf.py
Labels: tools

#1170 CSLA Compat - Fix typo in LICENSE filename
  optionals/sys_csla/LICENSE
Labels: cleanup, ignore changelog, compatibility
