Repository IDI-Systems/acre2, pull requests merged in 2021-08, with the labels that each got.

#1124 Antenna - Make 1.23M VHF TNC compatible with AN/PRC-152
  addons/sys_antenna/CfgAcreComponents.hpp
Labels: bug fix, ignore changelog

#1106 Add SQFC Support
  .github/workflows/release.yml
  .gitignore
  addons/ace_interact/CfgEventHandlers.hpp
  addons/api/CfgEventHandlers.hpp
  addons/main/CfgEventHandlers.hpp
  addons/main/script_mod.hpp
  addons/sys_antenna/CfgEventHandlers.hpp
  addons/sys_attenuate/CfgEventHandlers.hpp
  addons/sys_components/CfgEventHandlers.hpp
  addons/sys_core/CfgEventHandlers.hpp
  addons/sys_data/CfgEventHandlers.hpp
  addons/sys_external/CfgEventHandlers.hpp
  addons/sys_gestures/CfgEventHandlers.hpp
  addons/sys_godmode/CfgEventHandlers.hpp
  addons/sys_gsa/CfgEventHandlers.hpp
  addons/sys_gui/CfgEventHandlers.hpp
  addons/sys_intercom/CfgEventHandlers.hpp
  addons/sys_io/CfgEventHandlers.hpp
  addons/sys_list/CfgEventHandlers.hpp
  addons/sys_modes/CfgEventHandlers.hpp
  addons/sys_prc117f/CfgEventHandlers.hpp
  addons/sys_prc148/CfgEventHandlers.hpp
  addons/sys_prc152/CfgEventHandlers.hpp
  addons/sys_prc343/CfgEventHandlers.hpp
  addons/sys_prc77/CfgEventHandlers.hpp
  addons/sys_rack/CfgEventHandlers.hpp
  addons/sys_radio/CfgEventHandlers.hpp
  addons/sys_rpc/CfgEventHandlers.hpp
  addons/sys_sem52sl/CfgEventHandlers.hpp
  addons/sys_sem70/CfgEventHandlers.hpp
  addons/sys_server/CfgEventHandlers.hpp
  addons/sys_signal/CfgEventHandlers.hpp
  addons/sys_signalmap/CfgEventHandlers.hpp
  addons/sys_sounds/CfgEventHandlers.hpp
  addons/sys_spectator/CfgEventHandlers.hpp
  addons/sys_zeus/CfgEventHandlers.hpp
  docs/wiki/development/building.md
  hemtt.toml
  include/a3/ui_f/hpp/defineCommonColors.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineResincl.inc
  include/x/cba/addons/main/script_macros_common.hpp
  optionals/sys_sog/CfgEventHandlers.hpp
  sqfc.json
  tools/compile_sqf.py
  tools/setup.bat
  tools/updateIncludes.py
Labels: tools

#1117 Documentation - Add Antennas and Gain Pattern Videos
  docs/_data/sidebar.yml
  docs/wiki/class-names.md
  docs/wiki/user/basic-concepts.md
Labels: documentation

#1114 PRC117F/PRC152 - Add missing hashes to `getChannelData` event
  addons/sys_prc117f/radio/fnc_getChannelData.sqf
  addons/sys_prc152/radio/fnc_getChannelData.sqf
Labels: enhancement

#1130 Translations - Improve Spanish
  addons/ace_interact/stringtable.xml
  addons/api/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_spectator/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation
