Repository IDI-Systems/acre2, pull requests merged in 2021-10, with the labels that each got.

#1139 API - Fix `filterUnitLoadout` for empty loadouts
  addons/api/fnc_filterUnitLoadout.sqf
Labels: bug fix

#1142 General - Add Turkish Translations
  addons/ace_interact/stringtable.xml
  addons/api/stringtable.xml
  addons/main/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_godmode/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_signal/stringtable.xml
  addons/sys_spectator/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#1143 Tools - Update stringtable checks
  .github/workflows/arma.yml
  addons/sys_spectator/stringtable.xml
  addons/sys_zeus/initSettings.sqf
  tools/stringtable_checkDefined.py
  tools/stringtable_validator.py
Labels: tools

#1144 General - Cleanup redundant string defines
  addons/sys_data/script_strings.hpp
  addons/sys_prc117f/script_strings.hpp
  addons/sys_prc148/script_strings.hpp
  addons/sys_prc152/script_strings.hpp
  addons/sys_prc343/script_strings.hpp
  addons/sys_prc77/script_strings.hpp
  addons/sys_radio/script_strings.hpp
  addons/sys_sem52sl/script_strings.hpp
  addons/sys_sem70/script_strings.hpp
  addons/sys_sounds/script_strings.hpp
Labels: cleanup
