Repository IDI-Systems/acre2, pull requests merged in 2023-08, with the labels that each got.

#1266 Radio - Fix Half-Duplex keying not muting ongoing transmissions
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_speaking.sqf
Labels: bug fix

#1255 Racks - Fix vehicle racks unable to use certain intercoms
  addons/sys_rack/fnc_configWiredIntercoms.sqf
Labels: bug fix

#1265 Racks/Intercom - Enable without ACE Interaction Menu (requires Intercom to access racked radios)
  .hemtt/project.toml
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_rack/XEH_postInit.sqf
  docs/wiki/user/vehicle-intercom.md
  docs/wiki/user/vehicle-racks.md
Labels: enhancement

#1268 Extensions - Require CMake 3.10
  extensions/src/ACRE2Arma/CMakeLists.txt
  extensions/src/ACRE2Arma/acre/CMakeLists.txt
  extensions/src/ACRE2Arma/arma2ts/CMakeLists.txt
  extensions/src/ACRE2Core/CMakeLists.txt
  extensions/src/ACRE2DistortionTestPlugin/CMakeLists.txt
  extensions/src/ACRE2Shared/CMakeLists.txt
  extensions/src/ACRE2Steam/CMakeLists.txt
  extensions/src/Wav2B64/CMakeLists.txt
Labels: task, ignore changelog

#1269 Docs - Fix intercom example code
  .gitignore
  docs/wiki/frameworks/vehicle-intercom.md
Labels: documentation, ignore changelog

#1273 BF-888S - Use `COMPILE_SCRIPT` macro
  addons/sys_bf888s/CfgEventHandlers.hpp
Labels: optimization, ignore changelog
