Repository IDI-Systems/acre2, pull requests merged in 2023-10, with the labels that each got.

#1292 Core - Show error if plugin not found
  addons/sys_core/XEH_postInit.sqf
Labels: enhancement

#1294 External - Share radios when unconscious
  addons/sys_external/fnc_getSharedExternalRadios.sqf
Labels: enhancement

#1277 Documentation - Add Creator DLC Compatibility information
  addons/compat_csla/README.md
  addons/compat_gm/README.md
  addons/compat_sog/README.md
  addons/compat_spe/README.md
  addons/compat_ws/README.md
  docs/css/customstyles.css
  docs/images/compats/acre2_csla_compat_small-logo.png
  docs/images/compats/acre2_gm_compat_small-logo.png
  docs/images/compats/acre2_sog_compat_small-logo.png
  docs/images/compats/acre2_spe_compat_small-logo.png
  docs/images/compats/acre2_ws_compat_small-logo.png
  docs/wiki/user/feature-list.md
Labels: documentation

#1299 CI - Update actions/checkout to v4
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
  .github/workflows/release.yml
Labels: tools, ignore changelog
