Repository IDI-Systems/acre2, pull requests merged in 2023-05, with the labels that each got.

#1223 Attenuate - Add helper for diagnosing compartment attenuation behavior
  addons/sys_attenuate/XEH_PREP.hpp
  addons/sys_attenuate/fnc_debugDraw.sqf
  addons/sys_attenuate/fnc_toggleDebugInfo.sqf
  docs/images/attenuation/attenuate_debuginfo.jpg
  docs/wiki/frameworks/vehicle-attenuation.md
Labels: documentation, feature request

#1244 Translations - Improve and fix portuguese translation
  addons/ace_interact/stringtable.xml
  addons/api/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_godmode/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_spectator/stringtable.xml
Labels: translation

#1245 I/O - Don't show pipe disconnected warning in Eden Preview
  addons/sys_io/fnc_server.sqf
Labels: enhancement

#1186 API - Add VOIP Information / Enforcer Required API
  .hemtt/project.toml
  addons/api/CfgFunctions.hpp
  addons/api/fnc_getVOIPChannelName.sqf
  addons/api/fnc_getVOIPChannelUID.sqf
  addons/api/fnc_getVOIPServerName.sqf
  addons/api/fnc_getVOIPServerUID.sqf
  addons/api/fnc_isVOIPConnected.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_postInit.sqf
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_handleGetVOIPChannelName.sqf
  addons/sys_core/fnc_handleGetVOIPChannelUID.sqf
  addons/sys_core/fnc_handleGetVOIPServerName.sqf
  addons/sys_core/fnc_handleGetVOIPServerUID.sqf
  addons/sys_core/fnc_updateVOIPInfo.sqf
  addons/sys_core/fnc_utilityFunction.sqf
  extensions/src/ACRE2Core/Engine.cpp
  extensions/src/ACRE2Core/getVOIPChannelName.h
  extensions/src/ACRE2Core/getVOIPChannelUID.h
  extensions/src/ACRE2Core/getVOIPServerName.h
  extensions/src/ACRE2Core/getVOIPServerUID.h
  extensions/src/ACRE2DistortionTestPlugin/TS3Client.cpp
  extensions/src/ACRE2DistortionTestPlugin/TS3Client.h
  extensions/src/ACRE2Shared/IClient.h
  extensions/src/ACRE2TS/TS3Client.cpp
  extensions/src/ACRE2TS/TS3Client.h
Labels: feature request

#1242 Signal Map - Fix Zero Divisor on map generation start
  addons/sys_signalmap/fnc_doProcess.sqf
Labels: bug fix

#1246 Tools - Rename HEMTT release zip
  .hemtt/hooks/post_release/01_notes.rhai
  .hemtt/hooks/post_release/01_rename_zip.rhai
  docs/wiki/development/building.md
Labels: tools
