Repository IDI-Systems/acre2, pull requests merged in 2023-09, with the labels that each got.

#1276 Misc - Trivial cleanup for 2.14
  addons/main/CfgSettings.hpp
  addons/main/script_mod.hpp
  include/a3/ui_f/hpp/defineResincl.inc
  tools/compile_sqf.py
Labels: ignore changelog

#1279 Tools - Remove old Jenkins and publishing tools
  manifest.json
  tools/jenkins.py
  tools/publish.py
Labels: cleanup, ignore changelog

#1278 CI - Remove compatibility publishing
  .github/workflows/release.yml
Labels: cleanup, ignore changelog

#1281 Extensions - Fix TeamSpeak v3.6.0 deadlock
  extensions/src/ACRE2Core/updateSpeakingData.h
Labels: bug fix

#1280 General - Relative `script_component.hpp` includes
  addons/sys_intercom/vic3/script_component.hpp
  addons/sys_prc117f/farris_menus/script_component.hpp
  addons/sys_prc117f/menus/script_component.hpp
  addons/sys_prc117f/menus/types/script_component.hpp
  addons/sys_prc117f/radio/script_component.hpp
  addons/sys_prc148/menus/script_component.hpp
  addons/sys_prc148/radio/script_component.hpp
  addons/sys_prc148/states/AccessDenied.sqf
  addons/sys_prc148/states/ChannelDisplays.sqf
  addons/sys_prc148/states/Group.sqf
  addons/sys_prc148/states/MainDisplays.sqf
  addons/sys_prc148/states/ModeDisplays.sqf
  addons/sys_prc148/states/OffDisplay.sqf
  addons/sys_prc148/states/ProgramDisplays.sqf
  addons/sys_prc148/states/ProgrammingDisplays.sqf
  addons/sys_prc148/states/StartUp.sqf
  addons/sys_prc152/farris_menus/script_component.hpp
  addons/sys_prc152/menus/script_component.hpp
  addons/sys_prc152/menus/types/script_component.hpp
  addons/sys_prc152/radio/script_component.hpp
  addons/sys_prc77/functions/script_component.hpp
  addons/sys_prc77/radio/script_component.hpp
  addons/sys_rack/sem90/script_component.hpp
  addons/sys_rack/vrc103/script_component.hpp
  addons/sys_rack/vrc110/script_component.hpp
  addons/sys_rack/vrc111/script_component.hpp
  addons/sys_rack/vrc64/script_component.hpp
Labels: enhancement, ignore changelog

#1287 Documentation - Fix mission making intro API links
  docs/wiki/frameworks/mission-making-intro.md
Labels: bug fix, documentation, ignore changelog

#1285 BF-888S - Show current channel on channel knob
  addons/sys_bf888s/functions/fnc_render.sqf
Labels: enhancement

#1288 Radios - Localize some radio UI tooltips
  addons/sys_bf888s/bf888s_RadioDialog.hpp
  addons/sys_bf888s/functions/fnc_render.sqf
  addons/sys_intercom/vic3/vic3_ffcs_intercomDialog.hpp
  addons/sys_prc148/fnc_render.sqf
  addons/sys_prc148/menus/fnc_onVolumeKnobPress.sqf
  addons/sys_prc148/prc148_RadioDialog.hpp
  addons/sys_prc152/prc152_RadioDialog.hpp
  addons/sys_prc343/functions/fnc_render.sqf
  addons/sys_prc343/prc343_RadioDialog.hpp
  addons/sys_radio/stringtable.xml
  addons/sys_sem52sl/sem52sl_RadioDialog.hpp
  addons/sys_sem70/sem70_RadioDialog.hpp
Labels: enhancement

#1271 Racks - Add Use to Intercom-Radios and Increase access on MRAPs
  addons/sys_rack/CfgVehicles.hpp
  addons/sys_rack/XEH_PREP.hpp
  addons/sys_rack/fnc_getRackLetterFromRadio.sqf
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/script_component.hpp
  addons/sys_rack/stringtable.xml
Labels: enhancement, bug fix

#1284 Racks - Fix AN/VRC-64 (PRC-77) connector
  README.md
  addons/sys_components/fnc_attachComplexComponent.sqf
  addons/sys_components/script_acre_component_defines.hpp
  addons/sys_prc77/CfgAcreRadios.hpp
  addons/sys_rack/CfgAcreRacks.hpp
  addons/sys_rack/vrc64/fnc_vrc64MountRadio.sqf
  docs/wiki/frameworks/vehicle-racks.md
  docs/wiki/user/vehicle-racks.md
Labels: bug fix, documentation

#1253 Compat SOG - Improve Racks and Attenuation configs
  .hemtt/project.toml
  addons/compat_sog/CfgVehicles.hpp
  addons/compat_sog/config.cpp
Labels: enhancement, compatibility

#1283 Radio - Add radio item replacement CBA Setting
  addons/api/CfgAcreAPI.hpp
  addons/api/CfgModules.hpp
  addons/api/config.cpp
  addons/api/fnc_basicMissionSetup.sqf
  addons/api/fnc_getAllRadios.sqf
  addons/api/fnc_setItemRadioReplacement.sqf
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/fnc_getAllRadios.sqf
  addons/sys_core/script_component.hpp
  addons/sys_radio/XEH_preInit.sqf
  addons/sys_radio/fnc_monitorRadios.sqf
  addons/sys_radio/fnc_monitorRadiosPFH.sqf
  addons/sys_radio/initSettings.sqf
  addons/sys_radio/stringtable.xml
Labels: enhancement

#1289 Tools - Fix configs for HEMTT v1.9.0
  addons/compat_spe/SPE_Tanks.hpp
  addons/sys_gsa/CfgWeapons.hpp
  addons/sys_list/script_component.hpp
  include/a3/ui_f/hpp/defineResincl.inc
  include/x/cba/addons/main/script_macros_common.hpp
Labels: tools, ignore changelog
