Repository IDI-Systems/acre2, pull requests merged in 2023-04, with the labels that each got.

#1234 Data - Fix data sync causing hitching with large data due to logging
  addons/sys_data/XEH_preInit.sqf
  addons/sys_data/fnc_clientHandleJipData.sqf
  addons/sys_data/fnc_serverHandleJip.sqf
Labels: optimization

#1240 Extension - Handle stereo audio from TeamSpeak (cherry pick)
  extensions/src/ACRE2Core/FilterPosition.cpp
  extensions/src/ACRE2Core/SoundEngine.cpp
  extensions/src/ACRE2Core/SoundMonoChannel.cpp
  extensions/src/ACRE2Core/SoundMonoChannel.h
  extensions/src/ACRE2Core/SoundPlayback.cpp
Labels: bug fix

#1205 Core - Filter radios for CBA Extended Loadouts
  addons/sys_core/XEH_postInit.sqf
Labels: enhancement
