Repository IDI-Systems/acre2, pull requests merged in 2024-12, with the labels that each got.

#1354 Attenuation - Fix missing `MrapAttenuation` Sound Effect
  addons/sys_attenuate/CfgSoundEffects.hpp
Labels: bug fix

#1348 SYS_PRC117F - Fix channel name return
  addons/sys_prc117f/radio/fnc_getChannelData.sqf
Labels: bug fix, trivial

#1353 PRC117F/PRC152 - Fix undefined macro
  .hemtt/lints.toml
  addons/sys_prc117f/script_component.hpp
  addons/sys_prc152/script_component.hpp
Labels: cleanup

#1357 Core - Fix Fast Channel Switch of VRC-64
  addons/api/fnc_getRadioChannel.sqf
  addons/api/fnc_setRadioChannel.sqf
  addons/sys_core/fnc_switchChannelFast.sqf
  addons/sys_prc77/radio/fnc_getCurrentChannel.sqf
Labels: bug fix

#1310 Extension - Fix array index out-of-bounds
  extensions/src/ACRE2Core/AcreDsp.cpp
Labels: bug fix

#1355 Compat - RHS USAF and AFRF
  addons/compat_rhs_afrf3/$PBOPREFIX$
  addons/compat_rhs_afrf3/CfgVehicles.hpp
  addons/compat_rhs_afrf3/config.cpp
  addons/compat_rhs_afrf3/script_component.hpp
  addons/compat_rhs_usf3/$PBOPREFIX$
  addons/compat_rhs_usf3/CfgVehicles.hpp
  addons/compat_rhs_usf3/config.cpp
  addons/compat_rhs_usf3/script_component.hpp
Labels: compatibility

#1290 Core - Add PhysX Ropes as "connector wires" for Infantry-Phone/GSA/External
  addons/sys_core/CfgVehicles.hpp
  addons/sys_core/XEH_PREP.hpp
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/config.cpp
  addons/sys_core/data/wire.cfg
  addons/sys_core/data/wire.p3d
  addons/sys_core/fnc_handleConnectorRope.sqf
  addons/sys_core/script_component.hpp
  addons/sys_gestures/initSettings.inc.sqf
  addons/sys_gestures/stringtable.xml
  addons/sys_gsa/fnc_connectServer.sqf
  addons/sys_gsa/fnc_disconnectServer.sqf
  addons/sys_gsa/fnc_externalAntennaPFH.sqf
  addons/sys_gsa/fnc_handleMast.sqf
  addons/sys_intercom/XEH_postInit.sqf
  addons/sys_intercom/fnc_infantryPhoneChildrenActions.sqf
  addons/sys_intercom/fnc_updateInfantryPhoneStatus.sqf
  addons/sys_intercom/stringtable.xml
Labels: feature request

#1325 PRC152 - Previous/Next Channel Stepping via PRE+/- instead of Knob
  addons/sys_core/fnc_switchChannelFast.sqf
Labels: enhancement, discussion

#1334 Rack - API and Usability Improvements
  addons/api/CfgFunctions.hpp
  addons/api/fnc_addRackToVehicle.sqf
  addons/api/fnc_removeAllRacksFromVehicle.sqf
  addons/api/fnc_removeRackFromVehicle.sqf
  addons/api/fnc_replaceRacksOnVehicle.sqf
  addons/api/fnc_setMultiPushToTalkAssignment.sqf
  addons/sys_gui/RscTitles.hpp
  addons/sys_gui/fnc_updateVehicleInfo.sqf
  addons/sys_intercom/fnc_getStationVariableName.sqf
  addons/sys_rack/fnc_addRackOnReturn.sqf
  addons/sys_rack/fnc_enterVehicle.sqf
  addons/sys_rack/fnc_initVehicle.sqf
  addons/sys_rack/fnc_rackChildrenActions.sqf
  addons/sys_rack/fnc_startUsingMountedRadio.sqf
  addons/sys_rack/fnc_stopUsingMountedRadio.sqf
  addons/sys_rack/stringtable.xml
  docs/_includes/custom/functions-list-api.html
  docs/wiki/frameworks/vehicle-racks.md
Labels: feature request

#1339 Add 'acre_api_fnc_getRadioOnOffState' to accessible method
  addons/api/CfgFunctions.hpp
  addons/api/fnc_getRadioOnOffState.sqf
  addons/sys_radio/XEH_PREP.hpp
  addons/sys_radio/fnc_getRadioOnOffState.sqf
  docs/_includes/custom/functions-list-api.html
Labels: feature request

#1336 GUI - Allow Volume Control during ACE Progressbar Dialog
  addons/sys_gui/fnc_volumeKeyDown.sqf
Labels: enhancement

#1347 Add default password for TS3 channel
  extensions/src/ACRE2DistortionTestPlugin/TS3Client.cpp
  extensions/src/ACRE2TS/TS3Client.cpp
Labels: enhancement

#1362 Core - Fix `acre_infantryPhonePosition` position
  addons/sys_core/fnc_handleConnectorRope.sqf
Labels: ignore changelog

#1364 GUI - Fix Volume Control dialog logic
  addons/sys_gui/fnc_volumeKeyDown.sqf
  addons/sys_io/fnc_ts3ChannelMove.sqf
Labels: bug fix, ignore changelog

#1363 General - Optimize in-vehicle checks
  .hemtt/lints.toml
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_core/fnc_hasAccessToVehicleSystem.sqf
  addons/sys_core/fnc_switchChannelFast.sqf
  addons/sys_external/fnc_isExternalRadioAvailable.sqf
  addons/sys_external/fnc_radioCheckChildrenActions.sqf
  addons/sys_intercom/fnc_updateVehicleInfoText.sqf
  addons/sys_prc117f/radio/fnc_setState.sqf
  addons/sys_rack/XEH_postInit.sqf
  addons/sys_rack/fnc_isRackAccessible.sqf
  addons/sys_rack/fnc_isRackHearable.sqf
  addons/sys_rack/fnc_rackPFH.sqf
  addons/sys_spectator/fnc_handleStartedSpeaking.sqf
  addons/sys_spectator/fnc_handleStoppedSpeaking.sqf
Labels: optimization
