Repository IDI-Systems/acre2, pull requests merged in 2024-09, with the labels that each got.

#1345 CI - Fix HEMTT CI artifacts not uploaded
  .github/workflows/arma.yml
  .github/workflows/release.yml
Labels: tools

#1343 Common - Update for HEMTT 1.13
  .hemtt/lints.toml
  addons/sys_attenuate/fnc_debugDraw.sqf
  addons/sys_bf888s/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_components/fnc_findAntenna.sqf
  addons/sys_components/fnc_getAntennaDirMan.sqf
  addons/sys_core/fnc_processDirectSpeaker.sqf
  addons/sys_core/fnc_removeGear.sqf
  addons/sys_core/fnc_replaceGear.sqf
  addons/sys_core/fnc_updateSelf.sqf
  addons/sys_external/fnc_listChildrenActions.sqf
  addons/sys_external/fnc_startUsingExternalRadio.sqf
  addons/sys_external/fnc_stopUsingExternalRadio.sqf
  addons/sys_gsa/fnc_connectChildrenActions.sqf
  addons/sys_gui/fnc_antennaElevationDisplay.sqf
  addons/sys_gui/fnc_updateVehicleInfo.sqf
  addons/sys_list/fnc_cycleRadios.sqf
  addons/sys_prc117f/farris_menus/SQ.sqf
  addons/sys_prc117f/radio/fnc_handleEndTransmission.sqf
  addons/sys_prc148/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc152/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_prc343/functions/fnc_render.sqf
  addons/sys_rack/fnc_generateMountableRadioActions.sqf
  addons/sys_radio/fnc_onPlayerKilled.sqf
  addons/sys_sem52sl/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_sem70/radio/fnc_getExternalAudioPosition.sqf
  addons/sys_server/fnc_doAddComponentCargo.sqf
  addons/sys_server/fnc_onGetRadioId.sqf
  addons/sys_signalmap/fnc_doProcess.sqf
  addons/sys_signalmap/fnc_drawMenu.sqf
  addons/sys_signalmap/fnc_drawSignalMaps.sqf
  addons/sys_signalmap/fnc_showOverlayMessage.sqf
Labels: cleanup

#1333 Intercom - Fix config error
  addons/sys_intercom/CfgVehicles.hpp
Labels: bug fix, ignore changelog

#1337 Zeus - Voice source switch while Handcuffed/Surrendering
  addons/sys_zeus/CfgVehicles.hpp
Labels: bug fix

#1341 Translations - Add French
  addons/compat_spe/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation

#1305 Zeus - Fix remote control breaking Racks and resetting custom PTTs
  addons/api/fnc_getMultiPushToTalkAssignment.sqf
  addons/api/fnc_setMultiPushToTalkAssignment.sqf
  addons/sys_core/XEH_preInit.sqf
  addons/sys_core/fnc_handleMultiPttKeyPress.sqf
  addons/sys_rack/fnc_enterVehicle.sqf
  docs/wiki/user/vehicle-racks.md
Labels: bug fix
