Repository IDI-Systems/acre2, pull requests merged in 2024-07, with the labels that each got.

#1315 API - Filter radio IDs when setting unit loadouts via CBA
  addons/api/XEH_preInit.sqf
Labels: enhancement, CBA's fault

#1330 Translations - Add missing German, fully revise Italian
  addons/ace_interact/stringtable.xml
  addons/api/stringtable.xml
  addons/compat_spe/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_external/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_godmode/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_gui/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_spectator/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#1324 Babel - Persistent Language Hint for non-primary language
  addons/sys_core/fnc_cycleLanguage.sqf
  addons/sys_list/initSettings.inc.sqf
  addons/sys_list/stringtable.xml
Labels: feature request

#1331 Revert "Main - Replace Fast Hash system with native hashmaps"
  addons/main/CfgLocationTypes.hpp
  addons/main/XEH_PREP.hpp
  addons/main/XEH_preInit.sqf
  addons/main/config.cpp
  addons/main/fnc_fastHashCopy.sqf
  addons/main/fnc_fastHashCopyArray.sqf
  addons/main/fnc_fastHashCreate.sqf
  addons/main/fnc_fastHashKeys.sqf
  addons/main/fnc_garbageCollector.sqf
  addons/main/fnc_hashMonitor.sqf
  addons/main/script_macros.hpp
Labels: bug fix, ignore changelog

#1332 Main - Bump required CBA version
  addons/main/script_mod.hpp
Labels: ignore changelog
