Repository IDI-Systems/acre2, pull requests merged in 2025-01, with the labels that each got.

#1365 Translation - Add French
  addons/compat_spe/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_intercom/stringtable.xml
Labels: translation

#1366 Documentation - Explain variable Tx Power of PRC-77
  docs/wiki/radios/an-prc-77.md
Labels: documentation

#1367 Core - Fix GSA rope helper objects being placed below buildings
  addons/sys_core/fnc_handleConnectorRope.sqf
Labels: bug fix

#1368 Signal - Add climate code 4 to North Takistan (Longley-Rice)
  addons/sys_signal/CfgAcreSignal.hpp
Labels: enhancement

#1369 Translation - Improve Simplified Chinese
  addons/ace_interact/stringtable.xml
  addons/compat_spe/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_godmode/stringtable.xml
  addons/sys_gsa/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_io/stringtable.xml
  addons/sys_list/stringtable.xml
  addons/sys_rack/stringtable.xml
  addons/sys_radio/stringtable.xml
  addons/sys_spectator/stringtable.xml
  addons/sys_zeus/stringtable.xml
Labels: translation

#1370 Compat SPE - Fix string
  addons/compat_spe/compat_spex/config.cpp
Labels: ignore changelog

#1371 BF-888S - Optimize with `isNotEqualTo`
  addons/sys_bf888s/radio/fnc_handleMultipleTransmissions.sqf
Labels: optimization, trivial
