Repository IDI-Systems/acre2, pull requests merged in 2025-02, with the labels that each got.

#1373 Translation - Improve Japanese
  addons/compat_spe/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_gestures/stringtable.xml
  addons/sys_intercom/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation

#1372 Core - Use `fnc_getDescriptiveName` for all ACE Action Names
  addons/ace_interact/stringtable.xml
  addons/sys_core/fnc_getDescriptiveName.sqf
  addons/sys_external/fnc_listChildrenActions.sqf
  addons/sys_gsa/fnc_connectChildrenActions.sqf
  addons/sys_prc77/radio/fnc_getChannelDescription.sqf
  addons/sys_rack/fnc_generateMountableRadioActions.sqf
  addons/sys_sem52sl/radio/fnc_getChannelDescription.sqf
  addons/sys_sem70/radio/fnc_getChannelDescription.sqf
Labels: enhancement

#1374 Translation - Fix "Team" swapped between Japanese and Italian
  addons/main/stringtable.xml
Labels: bug fix

#1375 Translation - Improve Japanese
  addons/ace_interact/stringtable.xml
  addons/sys_gestures/stringtable.xml
Labels: translation

#1378 API - Fix Rack functions when called from 3DEN init box
  addons/api/fnc_initVehicleRacks.sqf
  addons/api/fnc_removeAllRacksFromVehicle.sqf
Labels: bug fix

#1381 Translations - Complete SPE Italian+German
  addons/compat_spe/stringtable.xml
  addons/sys_core/stringtable.xml
Labels: translation

#1386 Translation - French
  addons/ace_interact/stringtable.xml
  addons/sys_core/stringtable.xml
  addons/sys_radio/stringtable.xml
Labels: translation
